Fixed code errors

diff --git a/scripts/functions/init_stage3_seq b/scripts/functions/init_stage3_seq
--- a/scripts/functions/init_stage3_seq
+++ b/scripts/functions/init_stage3_seq
@@ -162,7 +162,7 @@ chk_snap_f() {
 }
 
 search_snap_f() {
-mapfile -t ARRAYSNAP < <(find /media/elab/workdir -name "*.tar.bz2")
+mapfile -t ARRAYSNAP < <(find / -name "*.tar.bz2")
 
 
 for i in "${ARRAYSNAP[@]}"; do
@@ -176,13 +176,15 @@ for i in "${ARRAYSNAP[@]}"; do
 						echo -e "\e[34mCopying snapshot to ${CATDIR}/snapshots\e[0m"
 						cp "$i" "${CATDIR}/snapshots/portage-${TARGETNAME}.tar.bz2"
 						return 0
+						ESCINNER=0
 						break
 						;;
 					[nN][oO]|[nN])
-						;;
+						ESCINNER=1
+						break;;
 				esac
 			done
-		break
+			[[ "$ESCINNER" == 0 ]] && unset ESCINNER && break
 		fi
 	fi
 done
@@ -253,7 +255,7 @@ while true; do
 			break;;
 		III|iii|3)
 			echo -e "\e[32mSearching\e[0m..."
-			search_snap_f && echo -e "\e[32mChecking\e[0m..." || { echo -e "\e[31mCould not locate the snapshot\e[0m"; BRKVAR=1; break; }
+			search_snap_f && echo -e "\e[32mChecking\e[0m..." || { echo -e "\e[31mCould not locate the snapshot\e[0m"; BRKVAR=1; }
 			echo -e "[\e[32m*\e[0m]  Located the snapshot"
 			if chk_snap_f "${CATDIR}/snapshots/portage-${TARGETNAME}.tar.bz2"; then
 				echo -e "[\e[32m*\e[0m]  Snapshot seems normal"
@@ -360,6 +362,9 @@ while true; do
 	esac
 	[[ "${BRKVAR}" == 0 ]] && break
 done
+else
+	echo -e "\e[32mPrtage snapshot found @ ${CATDIR}/snapshots\e[0m"
+
 fi
 unset BRKVAR
 unset TARGETNAME
@@ -370,7 +375,8 @@ unset TARGETPATH
 TARGETPATH="$(grep 'source_subpath' "${CONFDIR}/system/catalyst/stage1.spec" \
 | sed '/^#/ d' | awk -F ' ' '{ print $2 }' | sed  -e "s_\"__g" | awk -F '/' '{ print $1}')"
 
-if [[ -e "${CATDIR}/builds/${TARGETPATH}/${TARGETNAME}.tar.bz2" && "$3" == "s1" && ! -e "${CATDIR}/builds/${TARGETPATH}/stage1-amd64-${TARGETSTAMP}.tar.bz2" ]]; then
+stage1_f() {
+if [[ -e "${CATDIR}/builds/${TARGETPATH}/${TARGETNAME}.tar.bz2" ]]; then
 # STAGE 1
 
 echo -e "\e[35mBuilding stage1\e[0m"
@@ -380,6 +386,26 @@ cat "${CONFDIR}/system/catalyst/stage1.spec" | sed '/^#/ d' | sed '/^\s*$/d' \
 
 catalyst -c "${CONFDIR}/system/catalyst/catalyst.conf" -f "${CATDIR}/.stage1.spec" \
 && print_inf 1 || { print_inf 2 && exit 1; }
+else
+ echo -e "\e[31mCould not locate ${TARGETNAME}.tar.bz2\e[0m"
+fi
+}
+
+if [[ -e "${CATDIR}/builds/${TARGETPATH}/stage1-amd64-${TARGETSTAMP}.tar.bz2" && "$3" == "s1" ]]; then
+
+echo -e "\e[32mStage1 located\e[0m"
+
+while read -p "Do you wish to build new? Y/N " ANS; do
+	case $ANS in
+		[yY])
+			stage1_f
+			break;;
+		[nN])
+			break;;
+	esac
+done
+else
+stage1_f
 fi
 
 unset TARGETNAME
@@ -387,7 +413,8 @@ unset TARGETPATH
 unset TARGETSTAMP
 tar_path_name_f 2
 
-if [[ -e "${CATDIR}/builds/${TARGETPATH}/stage1-amd64-${TARGETSTAMP}.tar.bz2" && "$4" == "s2" && ! -e "${CATDIR}/builds/${TARGETPATH}/stage2-amd64-${TARGETSTAMP}.tar.bz2" ]]; then
+stage2_f() {
+if [[ -e "${CATDIR}/builds/${TARGETPATH}/stage1-amd64-${TARGETSTAMP}.tar.bz2" ]]; then
 # STAGE 2
 echo -e "\e[35mBuilding stage2\e[0m"
 
@@ -396,6 +423,26 @@ cat "${CONFDIR}/system/catalyst/stage2.spec" | sed '/^#/ d' | sed '/^\s*$/d' \
 
 catalyst -c "${CONFDIR}/system/catalyst/catalyst.conf" -f "${CATDIR}/.stage2.spec" \
 && print_inf 1 || { print_inf 2 && exit 1; }
+else
+ echo -e "\e[31mCould not locate stage1-amd64-${TARGETSTAMP}.tar.bz2\e[0m"
+fi
+}
+
+if [[ -e "${CATDIR}/builds/${TARGETPATH}/stage2-amd64-${TARGETSTAMP}.tar.bz2" && "$4" == "s2" ]]; then
+
+echo -e "\e[32mStage2 located\e[0m"
+
+while read -p "Do you wish to build new? Y/N " ANS; do
+	case $ANS in
+		[yY])
+			stage2_f
+			break;;
+		[nN])
+			break;;
+	esac
+done
+else
+stage2_f
 fi
 
 unset TARGETNAME
@@ -403,7 +450,8 @@ unset TARGETPATH
 unset TARGETSTAMP
 tar_path_name_f 3
 
-if [[ -e "${CATDIR}/builds/${TARGETPATH}/stage2-amd-64-${TARGETSTAMP}.tar.bz2" && "$5" == "s3" && ! -e "${CATDIR}/builds/${TARGETPATH}/stage3-amd64-${TARGETSTAMP}.tar.bz2" ]]; then
+stage3_f() {
+if [[ -e "${CATDIR}/builds/${TARGETPATH}/stage2-amd-64-${TARGETSTAMP}.tar.bz2" ]]; then
 # STAGE 3
 
 echo -e "\e[35mBuilding stage3\e[0m"
@@ -413,27 +461,29 @@ cat "${CONFDIR}/system/catalyst/stage3.spec" | sed '/^#/ d' | sed '/^\s*$/d' \
 
 catalyst -c "${CONFDIR}/system/catalyst/catalyst.conf" -f "${CATDIR}/.stage3.spec" \
 && print_inf 1 || { print_inf 2 && exit 1; }
+else
+ echo -e "\e[31mstage2-amd-64-${TARGETSTAMP}.tar.bz2\e[0m"
+fi
+}
 
-echo "The build was successful!"
-echo -e "\e[35mDo you wish to gpg sign the stage3 tarball?\e[0m"
-while true; do
-	read -rp "Answer: Y/N " YN
-	case "$YN" in
-		[yY][eE][sS]|[yY])
-			echo "Signing..."
-			gpg --sign "${CATDIR}/builds/${TARGETPATH}/stage3-amd64-${TARGETSTAMP}.tar.bz2" \
-			&& print_inf 1 || print_inf 2
-			echo "Returning back to parent..."
-			sleep 1
+if [[ -e "${CATDIR}/builds/${TARGETPATH}/stage3-amd64-${TARGETSTAMP}.tar.bz2" && "$5" == "s3" ]]; then
+
+echo -e "\e[32mStage3 located\e[0m"
+
+while read -p "Do you wish to build new? Y/N " ANS; do
+	case $ANS in
+		[yY])
+			stage3_f
 			break;;
-		[nN][oO]|[nN])
-			echo "Returning back to parent..."
-			sleep 1
-			;;
+		[nN])
+			break;;
 	esac
 done
+else
+stage3_f
 fi
 
+unset ANS
 unset TARGETNAME
 unset TARGETPATH
 unset TARGETSTAMP
