Configured force-new & fetch-new

diff --git a/scripts/chroot_scripts/cfunctions b/scripts/chroot_scripts/cfunctions
--- a/scripts/chroot_scripts/cfunctions
+++ b/scripts/chroot_scripts/cfunctions
@@ -73,7 +73,8 @@ chsinit_mon_f() {
 repeat_part_f() {
 while true; do
 	echo -e "\e[33mPart $1: Has been completed\e[0m"
-	read -rp "Run again? Y/N: " YN
+	echo -e "\e[33mRun again? Y/N: \e[0m"
+	read -rp "Input :: <= " YN
 	case "${YN}" in
 		[yN])
 			clear; eval "$2"
@@ -84,12 +85,43 @@ while true; do
 done
 }
 
+ex_sh_cont_f() {
+	while true; do
+		echo "Emerge could not complete that action"
+		echo "Do you wish to exit, check logs and fix it manually or continue"
+		echo -e "Answer: \e[31mEXIT\e[0m/\e[33mSHELL\e[0m/\e[34mCONTINUE\e[0m"
+		read -rp "Input :: <= " ANS
+		case "${ANS:-EXIT}" in
+			EXIT)
+				echo "Exiting..."
+				sleep 1
+				exit 1;;
+			SHELL)
+				while true; do
+					subshel_f
+					echo "Continue? Y/N: "
+					read -rp "Input :: <= " AANS
+					case "${AANS:-Y}" in
+						[yY])
+							break;;
+						[nN])
+							;;
+					esac
+				done
+				break;;
+			CONTINUE)
+				break;;
+		esac
+	done
+}
+
 emerge_resume_f() {
 	if [[ -n "$(grep "$2" <"${CHDIR}/emergeresume")" ]]; then
 		while true; do
 			echo -e "\e[33mA previous emerge action failed or stopped manually\e[0m"
-			echo -e "Do you wish to \e[34mresume\e[0m that action?"
-			read -rp "Answer Y/N: " YN
+			echo -e "Do you wish to \e[35mresume\e[0m that action?"
+			echo -e "Answer Y/N: "
+			read -rp "Input :: <= " YN
 			case "${YN:-y}" in
 				[yY])
 					echo -e "\e[33mResuming\e[0m"
@@ -108,7 +140,8 @@ emerge_resume_f() {
 							SHELL)
 								while true; do
 									subshel_f
-									read -rp "Continue? Y/N: " AANS
+									echo "Continue? Y/N: "
+									read -rp "Input :: <= " AANS
 									case "${AANS:-Y}" in
 										[yY])
 											break;;
@@ -147,92 +180,13 @@ emerge_dep_clean_f() {
 	&& emerge_resume_f "emerge --depclean" "DEPC"; }
 }
 
-port_prof_f() {
-	# GSE PROFILE DIRECTORIES AND FILES
-	mkdir -p /usr/local/portage/{metadata,profiles} \
-	&& chown -R portage:portage /usr/local/portage \
-	&& echo 'gse' > /usr/local/portage/profiles/repo_name \
-	&& cp "${CHDIR}/localrepo/layout.conf" "/usr/local/portage/metadata/layout.conf" \
-	&& cp "${CHDIR}/localrepo/localrepo.conf" "/etc/portage/repos.conf/localrepo.conf"
-
-	mkdir -p "/usr/local/portage/profiles/gse" \
-	&& mkdir -p "/usr/local/portage/profiles/default/linux/${ARCH}/13.0/gse" \
-	&& cp "${CHDIR}/profiles/parent-gse/eapi" \
-	"/usr/local/portage/profiles/gse/eapi" \
-	&& cp "${CHDIR}/profiles/parent-gse/make.defaults" \
-	"/usr/local/portage/profiles/gse/make.defaults" \
-	&& cp "${CHDIR}/profiles/parent-gse/package.use" \
-	"/usr/local/portage/profiles/gse/package.use" \
-	&& cp "${CHDIR}/profiles/parent-gse/package.use.force" \
-	"/usr/local/portage/profiles/gse/package.use.force" \
-	&& cp "${CHDIR}/profiles/child-gse/eapi" \
-	"/usr/local/portage/profiles/default/linux/${ARCH}/13.0/gse/eapi" \
-	&& cp "${CHDIR}/profiles/child-gse/parent" \
-	"/usr/local/portage/profiles/default/linux/${ARCH}/13.0/gse/parent" \
-	&& echo "# Local profile" > "/usr/local/portage/profiles/profiles.desc" \
-	&& echo "amd64           default/linux/amd64/13.0/gse                            exp" \
-	>> "/usr/local/portage/profiles/profiles.desc" \
-	&& echo -e "[\e[32m*\e[0m] Creating [\e[34mprofile\e[0m]" \
-	|| { echo -e "[\e[31m*\e[0m] Creating [\e[34profile\e[0m]"; return 1; }
-	# END OF GSE PROFILE
-}
-
-part_portage_f() {
-	# MAKE.CONF, PACKAGE.USE, FEATURES AND CCACHE
-	rm -f /etc/portage/make.conf \
-	&& rm -r /etc/portage/package.use/sysbuild >/dev/null 2>&1 \
-	&& mkdir -p "/etc/portage/package.use" \
-	&& cp "${CHDIR}/make.conf" /etc/portage/make.conf \
-	&& { echo -e "Configuring [\e[32mmake.conf\e[0m]" \
-	|| echo -e "\e[31mFaild\e[0m Configuring [\e[32mmake.conf\e[0m]"; } \
-	&& cp "${CHDIR}/package.use/sysbuild" "/etc/portage/package.use" \
-	&& { echo -e "Configuring [\e[32mpackage.use\e[0m]" \
-	|| echo -e "\e[31mFaild\e[0m Configuring [\e[32mpackage.use\e[0m]"; } \
-	&& echo "FEATURES=\"\${FEATURES} ${CHFEATURES}\"" >> /etc/portage/make.conf \
-	&& { echo -e "Configuring [\e[32mFEATURES\e[0m]" \
-	|| echo -e "\e[31mFaild\e[0m Configuring \e[32mFEATURES\e[0m"; } \
-	&& [[ -n "${CCCACHESIZE}" ]] && echo "CCACHE=\"${CCCACHESIZE}\"" >> /etc/portage/make.conf \
-	&& { echo -e "Configuring make.conf [\e[32mCCACHE=${CCCACHESIZE}\e[0m]" \
-	|| echo -e "\e[31mFaild\e[0m Failed configuring make.conf \e[32mCCACHE=${CCCACHESIZE}\e[0m"; } \
-	&& dist_ccashe_f \
-	&& emerge_resume_f "emerge_dep_clean_f" "DEPC" \
-	&& port_prof_f || return 1
-
-	# SELECTING PROFILE
-	echo -e "Do you wish to enable \e[33mGSE\e[0m \e[34mprofile\e[0m ::: (\e[31mexperimental\e[0m)?"
-	echo -e "Say no here, to select a basic \e[35mGentoo\e[0m \e[34mprofile\e[0m manually"
-	read -rp "Answer Y/N: " YN
-		while true; do
-		case "${YN:-n}" in
-			[yY])
-				GSE_PROF=$(eselect profile list | grep gse | awk -F '[' '{print $2}' | awk -F ']' '{print $1}') \
-				&& eselect profile set "${GSE_PROF}" && echo -e "\e[34mEnabled\e[0m" && BREAKVAR=0 \
-				|| { chprint_inf_f 2 && YN=n; };;
-			[nN])
-				eselect profile list
-				echo -e "Please select a \e[34mprofile\e[0m listed from above:"
-				echo -e "Answer is only related \e[34mprofile\e[0m numbers"
-				read -rp "Input :: <== " ANS
-					[[ -n "${ANS}" ]] && eselect profile set "${ANS}" && echo -e "\e[34mEnabled\e[0m" && BREAKVAR=0 \
-					|| { chprint_inf_f 2 && BREAKVAR=1; };;
-		esac
-	[[ "${BREAKVAR}" == 0 ]] && break \
-	|| { echo "Could not set a profile"
-	YN=n; }
-	done
-
-	unset YN
-	unset ANS
-	unset BREAKVAR
-}
-
 dist_ccashe_f() {
 	# ADD OR REMOVE DISTCC FROM THE SYSTEM
 	if [[ -n "$(echo ${CHFEATURES} | grep distcc)" ]]; then
-		if ! eix --installed sys-devel/distcc >/dev/null 2>&1 ]]; then
+		if ! eix --installed sys-devel/distcc >/dev/null 2>&1; then
 			echo -e "Configuring [\e[32mdistcc\e[0m]" \
 			&& emerge -q sys-devel/distcc >/dev/null 2>&1 \
-			&& chprint_inf 1 || chprint_inf 2
+			&& chprint_inf 1 || { chprint_inf 2 && return 1; }
 
 			mkdir -p /etc/distcc \
 			&& cp "${CHDIR}/hosts" /etc/distcc/hosts \
@@ -243,22 +197,122 @@ dist_ccashe_f() {
 		if eix --installed sys-devel/distcc >/dev/null 2>&1; then
 			echo -e "Removing [\e[32mdistcc\e[0m]" \
 			&& emerge --deselect sys-devel/distcc >/dev/null 2>&1 \
-			&& chprint_inf 1 || chprint_inf 2
+			&& chprint_inf 1
 		fi
 	fi
 	if [[ -n "${CCCACHESIZE}" ]]; then
 		if ! eix --installed dev-util/ccache >/dev/null 2>&1; then
 			echo -e "Configuring [\e[32mccache\e[0m]" \
 			&& emerge -q dev-util/ccache >/dev/null 2>&1 \
-			&& chprint_inf 1 || chprint_inf 2
+			&& chprint_inf 1 || { chprint_inf 2 && return 1; }
 		fi
 	else
 		if eix --installed dev-util/ccache >/dev/null 2>&1; then
 			echo -e "Removing [\e[33mccache\e[0m]" \
 			&& emerge --deselect sys-devel/distcc >/dev/null 2>&1 \
-			&& chprint_inf 1 || chprint_inf 2
+			&& chprint_inf 1
 		fi
 	fi
+}
+
+port_prof_f() {
+	# GSE PROFILE DIRECTORIES AND FILES
+	if mkdir -p /usr/local/portage/{metadata,profiles}; then
+		chown -R portage:portage /usr/local/portage || return 1
+		echo 'gse' > /usr/local/portage/profiles/repo_name || return 1
+		cp "${CHDIR}/localrepo/layout.conf" "/usr/local/portage/metadata/layout.conf" || return 1
+		cp "${CHDIR}/localrepo/localrepo.conf" "/etc/portage/repos.conf/localrepo.conf" || return 1
+		
+		mkdir -p "/usr/local/portage/profiles/gse" \
+		&& mkdir -p "/usr/local/portage/profiles/default/linux/${ARCH}/13.0/gse" \
+		&& cp "${CHDIR}/profiles/parent-gse/eapi" \
+		"/usr/local/portage/profiles/gse/eapi" \
+		&& cp "${CHDIR}/profiles/parent-gse/make.defaults" \
+		"/usr/local/portage/profiles/gse/make.defaults" \
+		&& cp "${CHDIR}/profiles/parent-gse/package.use" \
+		"/usr/local/portage/profiles/gse/package.use" \
+		&& cp "${CHDIR}/profiles/parent-gse/package.use.force" \
+		"/usr/local/portage/profiles/gse/package.use.force" \
+		&& cp "${CHDIR}/profiles/child-gse/eapi" \
+		"/usr/local/portage/profiles/default/linux/${ARCH}/13.0/gse/eapi" \
+		&& cp "${CHDIR}/profiles/child-gse/parent" \
+		"/usr/local/portage/profiles/default/linux/${ARCH}/13.0/gse/parent" \
+		&& echo "# Local profile" > "/usr/local/portage/profiles/profiles.desc" \
+		&& echo "amd64           default/linux/amd64/13.0/gse                            exp" \
+		>> "/usr/local/portage/profiles/profiles.desc" \
+		&& echo -e "[\e[32m*\e[0m] Creating [\e[34mprofile\e[0m]" \
+		|| { echo -e "[\e[31m*\e[0m] Creating [\e[34profile\e[0m]"; return 1; }
+	else
+		echo -e "[\e[31m*\e[0m] Creating [\e[34profile\e[0m]"
+		return 1
+	fi
+	# END OF GSE PROFILE
+}
+
+part_portage_f() {
+	# MAKE.CONF, PACKAGE.USE, FEATURES AND CCACHE
+	if rm -f /etc/portage/make.conf; then
+		rm -r /etc/portage/package.use/sysbuild >/dev/null 2>&1 || exit 1
+		mkdir -p "/etc/portage/package.use" || exit 1
+		cp "${CHDIR}/make.conf" /etc/portage/make.conf || exit 1
+		echo -e "Configuring [\e[32mmake.conf\e[0m]"
+		if cp "${CHDIR}/package.use/sysbuild" "/etc/portage/package.use"; then
+			echo -e "Configuring [\e[32mpackage.use\e[0m]"
+			echo "FEATURES=\"\${FEATURES} ${CHFEATURES}\"" >> /etc/portage/make.conf
+			echo -e "Configuring [\e[32mFEATURES\e[0m]"
+			if [[ -n "${CCCACHESIZE}" ]]; then
+				echo "CCACHE=\"${CCCACHESIZE}\"" >> /etc/portage/make.conf
+				echo -e "Configuring make.conf [\e[32mCCACHE=${CCCACHESIZE}\e[0m]"
+			fi
+
+			dist_ccashe_f || return 1
+			emerge_dep_clean_f "DEPC"
+			port_prof_f || return 1
+		else
+			echo -e "\e[31mFaild\e[0m Configuring [\e[32mpackage.use\e[0m]"
+			exit 1
+		fi
+	else
+		echo -e "\e[31mFaild\e[0m Configuring [\e[32mmake.conf\e[0m]"
+		exit 1
+	fi
+
+	if [[ -n $(echo $@ | grep '\--force-new') ]]; then
+		echo -e "\e[34Enabling basic profile\e[0m]"
+		eselect profile set 1 && echo -e "\e[34mEnabled\e[0m" && BREAKVAR=0 \
+		|| { chprint_inf_f 2 && YN=n; };;
+	else
+		# SELECTING PROFILE
+		echo -e "Do you wish to enable \e[33mGSE\e[0m \e[34mprofile\e[0m ::: (\e[31mexperimental\e[0m)?"
+		echo -e "Say no here, to select a basic \e[35mGentoo\e[0m \e[34mprofile\e[0m manually"
+		echo "Answer Y/N: "
+		read -rp "Input :: <= " YN
+		while true; do
+			case "${YN:-n}" in
+				[yY])
+					GSE_PROF=$(eselect profile list | grep gse | awk -F '[' '{print $2}' | awk -F ']' '{print $1}') \
+					&& eselect profile set "${GSE_PROF}" && echo -e "\e[34mEnabled\e[0m" && BREAKVAR=0 \
+					|| { chprint_inf_f 2 && YN=n; };;
+				[nN])
+					eselect profile list
+					echo -e "Please select a \e[34mprofile\e[0m listed from above:"
+					echo -e "Answer is only related \e[34mprofile\e[0m numbers"
+					read -rp "Input :: <= " ANS
+						[[ -n "${ANS}" ]] && eselect profile set "${ANS}" && echo -e "\e[34mEnabled\e[0m" && BREAKVAR=0 \
+						|| { chprint_inf_f 2 && BREAKVAR=1; };;
+			esac
+			if [[ "${BREAKVAR}" == 0 ]]; then
+				break 
+			else
+				echo "Could not set a profile"
+				YN=n
+			fi
+		done
+	fi
+
+	unset YN
+	unset ANS
+	unset BREAKVAR
 }
 
 apply_new_f() {
@@ -277,7 +331,8 @@ emerge_rebuild_system_f() {
 		echo "----------------------------------------------------------------------------"
 		echo "Do you wish to rebuild the system?"
 		echo "If catalyst built this system, simply say no"
-		read -rp "Answer Yes or No: " YN
+		echo "Answer Yes or No: "
+		read -rp "Input :: <= " YN
 		case "${YN:-n}" in
 			[yY][eE][sS]|[yY])
 				emerge -eq @world && chprint_inf 1 \
@@ -321,6 +376,11 @@ update_eix_f() {
 
 emerge_gentoolkit_f() {
  emerge -q app-portage/gentoolkit >/dev/null 2>&1
+}
+
+
+test_stage_f() {
+	echo -e "\e[31m$1\e[0m"
 }
 
 upd_port_em_eix_f() {
@@ -567,7 +627,8 @@ kernel_conf_f() {
 	while true; do
 		echo -e "Do you wish to configure the \e[34mkernel's\e[0m config file?"
 		echo -e "Please keep in mind that main function of the controller are related with \e[34mkernel builtins\e[0m"
-		read -rp "Select an option Y/N: " SELCT
+		echo -e "Select an option Y/N: "
+		read -rp "Input :: <= " SELCT
 			case ${SELCT:-y} in
 				[Yy][eE][sS]|[yY])
 					if genkernel --install kernel --menuconfig --kernel-config="${CHDIR}/kernel-conf" \
diff --git a/scripts/functions/catalyst_functions b/scripts/functions/catalyst_functions
--- a/scripts/functions/catalyst_functions
+++ b/scripts/functions/catalyst_functions
@@ -58,7 +58,8 @@ call_cata_f() {
 build_port() {
 	echo -e "\e[35mIt is strongly recommended to update your portdir first\e[0m"
 	while true; do
-		read -rp "Do you wish to update? Y/N " YN
+		echo "Do you wish to update? Y/N "
+		read -rp "Input :: <= " YN
 		case "${YN:-n}" in
 			[yY][eE][sS]|[yY])
 				echo -e "\e[32mUpdating...\e[0m"
@@ -72,7 +73,8 @@ build_port() {
 				} \
 				|| { echo -e "\e[31mUpdate failed, build without update?\e[0m"
 				while true; do
-					read -rp "Answer: YN " ANS
+					echo "Answer: YN "
+					read -rp "Input :: <= " ANS
 					case "${ANS:-n}" in
 						[yY])
 							echo -e "\e[34mProceeding\e[0m"
@@ -124,15 +126,14 @@ tar_path_name_f() {
 
 
 fetch_portage_f() {
-echo -e "[\e[31m*\e[0m] \e[31mFAILD\e[0m: Snapshot \e[31mverified\e[0m"
 if [[ -e "${CATDIR}/portage-latest.tar.bz2" ]]; then
 	echo -e "[\e[31m*\e[0m] Purging old snapshot" \
 	&& rm -f "${CATDIR}/portage-latest.tar.bz2"
-	# GETTING PORTAGE SNAPSHOT
 else
 	echo -e "[\e[31m*\e[0m] Local backup snapshot was not found!"
 fi
-	echo -e "[\e[32m*\e[0m] \e[34mGetting latest portage snapshot\e[0m" \
+	# FETCHING PORTAGE SNAPSHOT
+	echo -e "[\e[32m*\e[0m] \e[34mFetchinglatest portage snapshot\e[0m" \
 	&& wget -O "${CATDIR}/portage-latest.tar.bz2" \
 	http://distfiles.gentoo.org/snapshots/portage-latest.tar.bz2 >/dev/null 2>&1 \
 	&& print_inf 1 && return 0 || { print_inf 2; return 1; } 
@@ -145,26 +146,61 @@ verify_portage_f() {
 	|| { echo -e "[\e[31m*\e[0m] \e[31mFAILD\e[0m: Verifying \e[31mmd5sums\e[0m"; return 1; }
 }
 
-get_latest_portage_f() {
-	# PORTAGE MD5SUM
+port_md5sum_f() {
 	wget -O "${CATDIR}/portage-latest.tar.bz2.md5sum" \
 	http://distfiles.gentoo.org/snapshots/portage-latest.tar.bz2.md5sum >/dev/null 2>&1 \
-	&& echo -e "[\e[32m*\e[0m] \e[34mGetting md5sum\e[0m" \
-	|| { echo -e "[\e[31m*\e[0m] \e[31mFAILD\e[0m: \e[34mGetting md5sum\e[0m" \
+	&& echo -e "[\e[32m*\e[0m] \e[34mFetching md5sum\e[0m" \
+	|| { echo -e "[\e[31m*\e[0m] \e[31mFAILD\e[0m: \e[34mFetching md5sum\e[0m" \
 	&& return 1; }
-	
-	if verify_portage_f; then
-		echo "Copying to ${CATDIR}/snapshots" \
-		&& cp "${CATDIR}/portage-latest.tar.bz2" "${CATDIR}/snapshots/portage-${SNAPSHOTNAME}.tar.bz2" \
-		&& cp "${CATDIR}/portage-latest.tar.bz2.md5sum" "${CATDIR}/snapshots/portage-${SNAPSHOTNAME}.tar.bz2.md5sum" \
-		&& print_inf 1 && return 0 || { print_inf 2; return 1; }
+}
+
+simple_fetch_f() {
+	echo -e "[\e[32m*\e[0m] \e[34mFetching latest portage snapshot\e[0m" \
+	&& wget -O "${CATDIR}/portage-latest.tar.bz2" \
+	http://distfiles.gentoo.org/snapshots/portage-latest.tar.bz2 >/dev/null 2>&1 \
+	&& print_inf 1 && return 0 || { print_inf 2; return 1; }
+}
+
+get_latest_portage_f() {
+	if [[ -n $(echo "$@" | grep '\--force-new') ]]; then
+		echo -e "\e[33mForce new is active!\e[0m"
+		export_cat_dirs_f
+		rm -f "${CATDIR}/portage-latest.tar.bz2"
+		rm -f "${CATDIR}/portage-latest.tar.bz2.md5sum"
+		port_md5sum_f
+		simple_fetch_f
 	else
-		fetch_portage_f \
-		&& verify_portage_f \
-		&& echo "Copying to ${CATDIR}/snapshots" \
-		&& cp "${CATDIR}/portage-latest.tar.bz2" "${CATDIR}/snapshots/portage-${SNAPSHOTNAME}.tar.bz2" \
-		&& cp "${CATDIR}/portage-latest.tar.bz2.md5sum" "${CATDIR}/snapshots/portage-${SNAPSHOTNAME}.tar.bz2.md5sum" \
-		&& print_inf 1 && return 0 || { print_inf 2; return 1; }
+		if [[ -n $(echo "$@" | grep '\--fetch-new') || -n $(echo "$@" | grep '\-fn') ]]; then
+			[[ -z "$@" ]] && print_inf 4 && exit 1
+			export_cat_dirs_f
+			rm -f "${CATDIR}/portage-latest.tar.bz2"
+			rm -f "${CATDIR}/portage-latest.tar.bz2.md5sum"
+			echo -e "\e[33mSearching for portage snapshot...\e[0m"
+			# PORTAGE MD5SUM
+			port_md5sum_f
+			simple_fetch_f
+			verify_portage_f
+		else
+			# PORTAGE MD5SUM
+			if port_md5sum_f; then
+				if verify_portage_f; then
+					echo "Copying to ${CATDIR}/snapshots" \
+					&& cp "${CATDIR}/portage-latest.tar.bz2" "${CATDIR}/snapshots/portage-${SNAPSHOTNAME}.tar.bz2" \
+					&& cp "${CATDIR}/portage-latest.tar.bz2.md5sum" "${CATDIR}/snapshots/portage-${SNAPSHOTNAME}.tar.bz2.md5sum" \
+					&& print_inf 1 && return 0 || { print_inf 2; return 1; }
+				else
+					echo -e "[\e[31m*\e[0m] \e[31mFAILD\e[0m: Snapshot \e[31mverified\e[0m"
+					fetch_portage_f \
+					&& verify_portage_f \
+					&& echo "Copying to ${CATDIR}/snapshots" \
+					&& cp "${CATDIR}/portage-latest.tar.bz2" "${CATDIR}/snapshots/portage-${SNAPSHOTNAME}.tar.bz2" \
+					&& cp "${CATDIR}/portage-latest.tar.bz2.md5sum" "${CATDIR}/snapshots/portage-${SNAPSHOTNAME}.tar.bz2.md5sum" \
+					&& print_inf 1 && return 0 || { print_inf 2; return 1; }
+				fi
+			else
+				print_inf 1 && return 0 || { print_inf 2; return 1; }
+			fi
+		fi
 	fi
 }
 
@@ -186,7 +222,8 @@ for i in "${ARRAYSNAP[@]}"; do
 		if chk_snap_f "$i"; then
 			while true; do
 				echo "$i"
-				read -rp "Is this the snapshot? Y/N " YN
+				echo "Is this the snapshot? Y/N "
+				read -rp "Input :: <= " YN
 				case "${YN:-5}" in
 					[yY][eE][sS]|[yY])
 						echo -e "\e[34mCopying snapshot to ${CATDIR}/snapshots\e[0m"
@@ -230,13 +267,13 @@ stageX_f() {
 check_then_call_stageX_f() {
 	[[ -z "$@" ]] && print_inf 4 && return 1
 	if [[ -n $(echo $@ | grep '\--force-new') ]]; then
-		stageX_f "$1" "$2"
+		echo -e "\e[31mForce new is active!\e[0m"
+		#stageX_f "$1" "$2"
 	else
 		if [[ -e "${CATDIR}/builds/${TARGETPATH}/stage$2-${ARCH}-${TARGETSTAMP}.tar.bz2" && -n $(echo "$@" | grep "s$2") ]]; then
 
 			echo -e "\e[32mStage$2 located\e[0m"
-
-			while read -p "Do you wish to build new? Y/N " ANS; do
+			while read -p "Do you wish to build new? Y/N :: <= " ANS; do
 				case $ANS in
 					[yY])
 						stageX_f "$1" "$2"
diff --git a/scripts/functions/init_stage3_seq b/scripts/functions/init_stage3_seq
--- a/scripts/functions/init_stage3_seq
+++ b/scripts/functions/init_stage3_seq
@@ -8,6 +8,8 @@ LC_CTYPE="en_US.UTF-8"
 # PP CHECK
 [[ -z "$@" ]] && print_inf_f 4 && exit 1
 
+source "${CWORKDIR}/scripts/functions/catalyst_functions" || { echo -e "\e[32mMissing scripts\e[0m" && exit 1; }
+
 # EXPORT THE DIRECTORIES DEFINED BY STAGE1.SPEC
 export_cat_dirs_f
 
@@ -18,7 +20,7 @@ create_cata_dirs_f
 tar_path_name_f "1"
 
 if [[ ! -e "${CATDIR}/builds/${TARGETPATH}/${TARGETNAME}.tar.bz2" ]]; then
-cp "${CDISTDIR}/dists/stage3-${ARCH}-latest.tar.bz2" "${CATDIR}/builds/${TARGETPATH}/${TARGETNAME}.tar.bz2"
+	cp "${CDISTDIR}/dists/stage3-${ARCH}-latest.tar.bz2" "${CATDIR}/builds/${TARGETPATH}/${TARGETNAME}.tar.bz2"
 fi
 
 # CHECK IF SNAPSHOT EXISTS AND HAS NORMAL SIZE
@@ -30,20 +32,22 @@ while true; do
 	opt_f
 	echo -e "[\e[31m*\e[0m] Could not locate snapshots/portage-${SNAPSHOTNAME}.tar.bz2 @ ${CATDIR}/snapshots"
 	echo "Please select an option"
-	read -rp "Option: " ANS
+	read -rp "Input :: <= " ANS
 	case "$ANS" in
 		I|i|1)
-			get_latest_portage_f && BRKVAR=0 || BRKVAR=1
+			get_latest_portage_f "$@" && BRKVAR=0 || BRKVAR=1
 			;;
 		II|ii|2)
-			read -rp "Please enter the absolute path with the snapshot included: " PATHTOSNAP
+			echo "Please enter the absolute path with the snapshot included: "
+			read -rp "Input :: <= " PATHTOSNAP
 			if [[ -n "${PATHTOSNAP}" ]] && chk_snap_f "${PATHTOSNAP}"; then
 				cp "${PATHTOSNAP}" "${CATDIR}/snapshots/portage-${SNAPSHOTNAME}.tar.bz2" \
 				&& echo -e "\e[34mCopying snapshot to ${CATDIR}/snapshots\e[0m" && BRKVAR=0 || BTWRK=1				
 			else
 				echo -e "\e[31mThe file you entered is either a heavily modified snapshot or not a snapshot"
 				while true; do
-					read -rp "Do you wish to proceed? Y/N" YN
+					echo "Do you wish to proceed? Y/N"
+					read -rp "Input :: <= " YN
 					case "${YN:-n}" in
 						[yY][eE][sS]|[yY])
 							echo -e "\e[34mCopying file to ${CATDIR}/snapshots\e[0m"
@@ -69,7 +73,8 @@ while true; do
 			else
 				echo -e "[\e[31m*\e[0m] Snapshot located but it's size is out of normal boundaries"
 				while true; do
-					read -rp "Do you wish to continue? Y/N " YN
+					echo "Do you wish to continue? Y/N "
+					read -rp "Input :: <= " YN
 					case "${YN:-n}" in
 						[yY][eE][sS]|[yY])
 							echo -e "[\e[32m*\e[0m] Proceeding"
@@ -94,7 +99,8 @@ while true; do
 				else
 					echo -e "[\e[31m*\e[0m] Snapshot located but it's size is out of normal boundaries"
 					while true; do
-						read -rp "Do you wish to continue? Y/N " YN
+						echo "Do you wish to continue? Y/N "
+						read -rp "Input :: <= " YN
 						case "${YN:-n}" in
 							[yY][eE][sS]|[yY])
 								echo -e "[\e[32m*\e[0m] Proceeding"
@@ -117,21 +123,25 @@ while true; do
 			if [[ (($(ls -A "${CATPORTDIR}" | grep 'app-portage') != 'app-portage')) ]]; then
 				echo -e "[\e[32m*\e[0m] ${CATPORTDIR} does not look like a normal portage location"
 				while true; do
-					read -rp "Do you wish to continue? Y/N " YN
+					echo "Do you wish to continue? Y/N "
+					read -rp "Input :: <= " YN
 					case "${YN:-n}" in
 						[yY][eE][sS]|[yY])
 							build_port && echo -e "[\e[32m*\e[0m] Built" || echo -e "[\e[31m*\e[0m] Failed"
 							;;
 						[nN][oO]|[nN])
 							while true; do
-								read -rp "Do you wish to give a new portdir location? Y/N "
+								echo "Do you wish to give a new portdir location? Y/N "
+								read -rp "Input :: <= "
 								case $YN in
 									[yY][eE][sS]|[yY])
-										read -rp "Portdir's absolute path: " CATPORTDIR
+										echo "Portdir's absolute path: "
+										read -rp "Input :: <= " CATPORTDIR
 										if [[ (($(ls -A "${CATPORTDIR}" | grep 'app-portage') != 'app-portage')) ]]; then
 											echo "Neither this location looks to contain a normal portage directory"
 											while true; do
-												read -rp "Do you wish to proceed? Y/N "
+												echo "Do you wish to proceed? Y/N "
+												read -rp "Input :: <= "
 												case $YN in
 													[yY][eE][sS]|[yY])
 														export CATPORTDIR
@@ -171,11 +181,16 @@ unset BRKVAR
 }
 
 if [[ -n $(echo $@ | grep '\--force-new') ]]; then
-	echo -e "\e[34mCreating snapshot...\e[0m"
-	catalyst -s "${SNAPSHOTNAME}" && print_inf 1 || { print_inf 2 && exit 1; }
+	echo -e "\e[31mForce new is active!\e[0m"
+	if [[ ! -e "${CATDIR}/snapshots/portage-${SNAPSHOTNAME}.tar.bz2" ]]; then
+		get_latest_portage_f "$@" \
+		|| { echo -e "\e[34mCreating snapshot...\e[0m"
+		catalyst -s "${SNAPSHOTNAME}" && print_inf 1 || { print_inf 2 && exit 1; }; }
+	fi
 else
 	check_portage_snap_f
 fi
+
 # STAGE 1
 check_then_call_stageX_f "${CATDIR}/builds/${TARGETPATH}/${TARGETNAME}.tar.bz2" "1" "$@"
 unset TARGETNAME
diff --git a/scripts/functions/sinit_functions b/scripts/functions/sinit_functions
--- a/scripts/functions/sinit_functions
+++ b/scripts/functions/sinit_functions
@@ -15,7 +15,8 @@ subshel_f() {
 repeat_part_f() {
 while true; do
 	echo -e "\e[33mPart $1: Has been completed\e[0m"
-	read -rp "Run again? Y/N: " YN
+	echo "Run again? Y/N: "
+	read -rp "input :: <= " YN
 	case "${YN}" in
 		[yN])
 			return 0;;
@@ -25,6 +26,34 @@ while true; do
 done
 }
 
+popar_check_f() {
+c1="$(echo $@ | grep "\--cat")"
+f1="$(echo $@ | grep "\--fetch-new")"
+#f2="$(echo $@ | grep "\-precomp")"
+#if [[ $(echo $@ | grep --catalyst)]]
+
+}
+
+help_f() {
+	echo "Gentoo Stateless Environment, version: ${GSEVER}"
+	echo "Distributed under the GNU General Public License, V2"
+	echo "usage: gse [OPTIONS] / "
+	echo
+	echo "-fe, 	--fetch-new"
+	echo "-fcn,	--force-new"
+	echo "-lg,	--lawful-good"
+	echo "-ef, 	--enforce=x"
+	echo "-h, 	--help"
+	echo "-k, 	--keep"
+	echo "-hc, 	--health-check"
+	echo "-rpn,	--replace-new"
+	echo "-nk, 	--no-kernel"
+	echo "-ni, 	--no-initramfs"
+	echo "-bc, 	--build-controller"
+	echo "-bm, 	--build-minimal"
+
+	echo
+}
 
 calling_catalyst_f(){
 	echo -e "\e[34mCalling catalyst\e[0m"
@@ -43,21 +72,26 @@ catalyst_extr_tar_f() {
 	| sed '/^#/ d' | awk -F ' ' '{ print $2 }' | sed  -e "s_\"__g")" \
 	&& check_dir_f "${CATDIR}/builds/${TARGETPATH}/stage3-${ARCH}-${TARGETSTAMP}.tar.bz2" \
 	"${CDISTDIR}/workdir-catalyst" \
-	"${CATDIR}/snapshots/portage-${SNAPSHOTNAME}.tar.bz2" \
+	"${CATDIR}/snapshots/portage-${SNAPSHOTNAME}.tar.bz2" "$@" \
 	&& sinit_mon_f "EXTRACTION"
 }
 
 repeat_sub_part_f() {
-while true; do
-	echo -e "\e[33m$1: Has been $2\e[0m"
-	read -rp "Run again? Y/N: " YN
-	case "${YN}" in
-		[yN])
-			return 0;;
-		[nN])
-			return 9;;
-	esac
-done
+	while true; do
+		echo -e "\e[33m$1: Has been $2\e[0m"
+		if [[ -n $(echo "$@" | grep '\--force-new') ]]; then
+			:
+		else
+			echo "Run again? Y/N: "
+			read -rp "input :: <= " YN
+			case "${YN}" in
+				[yN])
+					return 0;;
+				[nN])
+					return 9;;
+			esac
+		fi
+	done
 }
 
 sinit_mon_f() {
@@ -94,8 +128,9 @@ dep_c_f() {
 		echo -e "\e[33mIf\e[0m \e[35meix\e[0m \e[33mis not installed, do no worry, it will get installed\e[0m"
 		echo
 		while true; do
-			read -rp "Check dependencies? Y/N: " YN
-			case "${YN:-n}" in
+			echo -e "\e[33mCheck dependencies? Y/N: \e[0m"
+			read -rp "Input :: <= " YN
+			case "${YN}" in
 				[yY])
 					echo -e "\e[34mChecking for dependencies\e[0m"
 					lcreq_f 1 || exit 1
@@ -117,7 +152,8 @@ dep_c_f() {
 		echo -e "\e[33mIf the all runtime dependencies are located, the process will continue, otherwise this window will exit. and expect you to manually install them\e[0m"
 		echo -e "\e[33mSince only Gentoo is officially upported, it is expected to manually install any missing dependencies\e[0m"
 		while true; do
-			read -rp "Check dependencies? Y/N: " YN
+			echo "Check dependencies? Y/N: "
+			read -rp "Input :: <= " YN
 			case "${YN:-n}" in
 				[yY])
 					echo -e "\e[34mChecking for dependencies\e[0m"
@@ -159,7 +195,11 @@ check_pds_f(){
 fundamentals_f() {
 	# CHECK FOR RUNTIME DEPENDENCIES
 	if [[ "$(awk -F '=' '/RDEP/{ print $2 }' <"${CLOCALLG}/sinprog")" == 0 ]]; then
-		dep_c_f
+		if [[ -n $(echo "$@" | grep '\--force-new') ]]; then
+			:
+		else
+			dep_c_f
+		fi
 	fi
 	
 	# CHECK IF THERE IS ANY WORK DONE
@@ -196,35 +236,13 @@ start_new_f() {
 				* ) echo "Wrong answer";;
 			esac
 		done
-elif [[ "$1" == "force_new" ]]; then
-	echo -e "\e[31mStart new parameter detected\e[0m"
-	echo -e "\e[34mIf you select yes, workdir will be purged\e[0m"
-	echo -e "\e[34mDo you wish to use this option\e[0m"
-	echo "Answer: Y/N "
-	while true; do
-		read -p "Give input :: <= " YN
-		case "${YN:-n}" in
-			[Yy][eE][sS]|[yY])
-				echo -e "\e[31mPurging...\e[0m" 
-				check_pds_f "$2" \
-				&& sinit_mon_f "RESET" && sed -i -e 's/1/0/g' "${CWORKDIR}/scripts/chroot_scripts/chsinprog"
-				break;;
-			[nN][oO]|[nN])
-				echo -e "\e[34mExiting...\e[0m"
-				exit 1;;
-			* ) echo "Wrong answer";;
-		esac
-	done
-fi
-unset YN
-}
-
-export_dist_f() {
-	export GENTOOKEY="$(lynx -dump ${SIGNING_KEY} |  grep "(4096-bit RSA)" | head -1 | awk -F '(' '{ print $1}')"
-	export "GENTOOKEY"
-	export GENTOOLATEST="$DIST/$(wget -q -O- "${DIST}/latest-stage3-$ARCH.txt" | tail -n 1 | awk -F ' ' '{ print $1 }')"
-	export STAGE3TB=$(wget -q -O- "${DIST}/latest-stage3-$ARCH.txt" | tail -n 1 | awk -F ' ' '{ print $1 }' | awk -F '/' '{ print $2 }')
-	export GENTOOLATESTASC="$DIST/$(wget -q -O- "${DIST}/latest-stage3-$ARCH.txt" | tail -n 1 | awk -F ' ' '{ print $1 }').DIGESTS.asc"
+	elif [[ "$1" == "force_new" ]]; then
+		echo -e "\e[31mForce new is active!\e[0m"
+		echo -e "\e[31mPurging workdir...\e[0m" 
+		check_pds_f "$2" \
+		&& sinit_mon_f "RESET" && sed -i -e 's/1/0/g' "${CWORKDIR}/scripts/chroot_scripts/chsinprog"
+	fi
+	unset YN
 }
 
 extract_tarball_f() {
@@ -244,30 +262,37 @@ extract_tarball_f() {
 
 check_dir_f() {
 	[[ -z "$@" && -d "$2" ]] && print_inf 4 && return 1
-	if [[ -d "$2" ]]; then
-		while true; do
-			echo -e "Seems that there already has been done some work at the \e[34mbuilderdir\e[0m"
-			echo "You could either continue from where you left, or backup/purge then start anew"
-			echo -e "Give one of: \e[32mCONTINUE\e[0m/\e[34mOLD\e[0m/\e[31mPURGE\e[0m "
-			read -rp "Input :: <= " ANS
-			case $ANS in
-				OLD)
-					echo "Backing up..."
-					mv "$2" "$2.old"
-					extract_tarball_f "$@"
-					break;;
-				PURGE)
-					echo "This may take some time"
-					echo "Purging..."
-					check_pds_f "$2"
-					extract_tarball_f "$@"
-					break;;
-				CONTINUE)
-					break;;
-			esac
-		done
-	else
+	if [[ -n $(echo "$@" | grep '\--force-new') ]]; then
+		echo "This may take some time"
+		echo "Purging..."
+		check_pds_f "$2"
 		extract_tarball_f "$@"
+	else
+		if [[ -d "$2" ]]; then
+			while true; do
+				echo -e "Seems that there already has been done some work at the \e[34mbuilderdir\e[0m"
+				echo "You could either continue from where you left, or backup/purge then start anew"
+				echo -e "Give one of: \e[32mCONTINUE\e[0m/\e[34mOLD\e[0m/\e[31mPURGE\e[0m "
+				read -rp "Input :: <= " ANS
+				case $ANS in
+					OLD)
+						echo "Backing up..."
+						mv "$2" "$2.old"
+						extract_tarball_f "$@"
+						break;;
+					PURGE)
+						echo "This may take some time"
+						echo "Purging..."
+						check_pds_f "$2"
+						extract_tarball_f "$@"
+						break;;
+					CONTINUE)
+						break;;
+				esac
+			done
+		else
+			extract_tarball_f "$@"
+		fi
 	fi
 }
 
@@ -283,6 +308,14 @@ amiroot() {
 	return 0
 }
 
+export_dist_f() {
+	export GENTOOKEY="$(lynx -dump ${SIGNING_KEY} |  grep "(4096-bit RSA)" | head -1 | awk -F '(' '{ print $1}')"
+	export "GENTOOKEY"
+	export GENTOOLATEST="$DIST/$(wget -q -O- "${DIST}/latest-stage3-$ARCH.txt" | tail -n 1 | awk -F ' ' '{ print $1 }')"
+	export STAGE3TB=$(wget -q -O- "${DIST}/latest-stage3-$ARCH.txt" | tail -n 1 | awk -F ' ' '{ print $1 }' | awk -F '/' '{ print $2 }')
+	export GENTOOLATESTASC="$DIST/$(wget -q -O- "${DIST}/latest-stage3-$ARCH.txt" | tail -n 1 | awk -F ' ' '{ print $1 }').DIGESTS.asc"
+}
+
 gentoo_key_f() {
 	[[ -z "${GENTOOKEY}" ]] && print_inf_f 4 && return 1
 	gpg --keyserver hkps.pool.sks-keyservers.net --recv-keys >/dev/null 2>&1 ${GENTOOKEY} \
@@ -293,18 +326,26 @@ gentoo_key_f() {
 get_latest_f() {
 	[[ -z "${GENTOOLATEST}" || -z "${GENTOOLATESTASC}" ]] && print_inf_f 4 && return 1
 	mkdir -p "${CDISTDIR}/dists" \
-	&& echo -e "[\e[32m*\e[0m] Getting \e[34m${STAGE3TB}\e[0m"
-	wget -c -O "${CDISTDIR}/dists/stage3-${ARCH}-latest.tar.bz2" "${GENTOOLATEST}" \
-	&& echo "${STAGE3TB}" > "${CDISTDIR}/dists/latest.info" \
-	&& print_inf_f 1 || { print_inf_f 2; return 1; }
-
+	&& echo -e "[\e[32m*\e[0m] Fetching \e[34m${STAGE3TB}\e[0m"
+	if [[ -n $(echo "$@" | grep '\--fetch-new') || -n $(echo "$@" | grep '\-fn') ]]; then
+		rm -f "${CDISTDIR}/dists/stage3-${ARCH}-latest.tar.bz2" >/dev/null 2>&1
+		rm -f "${CDISTDIR}/dists/stage3-${ARCH}-latest.tar.bz2.DIGESTS.asc" >/dev/null 2>&1
+		rm -f "${CDISTDIR}/dists/stage3-${ARCH}-latest.tar.bz2.DIGESTS" >/dev/null 2>&1
+		wget -c -O "${CDISTDIR}/dists/stage3-${ARCH}-latest.tar.bz2" "${GENTOOLATEST}" >/dev/null 2>&1 \
+		&& echo "${STAGE3TB}" > "${CDISTDIR}/dists/latest.info" \
+		&& print_inf_f 1 || { print_inf_f 2; return 1; }
+	else
+		wget -c -O "${CDISTDIR}/dists/stage3-${ARCH}-latest.tar.bz2" "${GENTOOLATEST}" \
+		&& echo "${STAGE3TB}" > "${CDISTDIR}/dists/latest.info" \
+		&& print_inf_f 1 || { print_inf_f 2; return 1; }
+	fi
 	wget -c -O "${CDISTDIR}/dists/stage3-${ARCH}-latest.tar.bz2.DIGESTS.asc" "${GENTOOLATESTASC}" >/dev/null 2>&1 \
-	&& echo -e "[\e[32m*\e[0m] Getting \e[34m${GENTOOLATEST}\e[0m" \
-	|| { echo -e "[\e[31m*\e[0m] \e[31mFAILD\e[0m: Getting \e[34m${GENTOOLATEST}\e[0m"; exit 1; }
+	&& echo -e "[\e[32m*\e[0m] Fetching \e[34m${GENTOOLATEST}\e[0m" \
+	|| { echo -e "[\e[31m*\e[0m] \e[31mFAILD\e[0m: Fetching \e[34m${GENTOOLATEST}\e[0m"; exit 1; }
 
 	wget -c -O "${CDISTDIR}/dists/stage3-${ARCH}-latest.tar.bz2.DIGESTS" "${GENTOOLATEST}.DIGESTS" >/dev/null 2>&1 \
-	&& echo -e "[\e[32m*\e[0m] Getting \e[34m${GENTOOLATEST}.DIGESTS\e[0m" \
-	|| { echo -e "[\e[31m*\e[0m] \e[31mFAILD\e[0m: Getting $\e[34m${GENTOOLATEST}.DIGESTS\e[0m"; exit 1; }
+	&& echo -e "[\e[32m*\e[0m] Fetching \e[34m${GENTOOLATEST}.DIGESTS\e[0m" \
+	|| { echo -e "[\e[31m*\e[0m] \e[31mFAILD\e[0m: Fetching $\e[34m${GENTOOLATEST}.DIGESTS\e[0m"; exit 1; }
 }
 
 verify_download_f() {
@@ -321,19 +362,8 @@ verify_download_f() {
 fetch_new_f() {
 	# CHECK FOR THE POSITIONAL PARAMETERS AND BAILOUT IF THEY ARE MISSING
 	[[ -z "$@" ]] && print_inf_f 4 && exit 1
-	echo -e "\e[34mSearching for tarball...\e[0m"
-	if [[ -n $(echo "$@" | grep '\--fetch-new') || -n $(echo "$@" | grep '\-fn') ]]; then
-		rm -f "${CDISTDIR}/dists/stage3-${ARCH}-latest.tar.bz2" >/dev/null 2>&1
-		rm -f "${CDISTDIR}/dists/stage3-${ARCH}-latest.tar.bz2.DIGESTS.asc" >/dev/null 2>&1
-		rm -f "${CDISTDIR}/dists/stage3-${ARCH}-latest.tar.bz2.DIGESTS" >/dev/null 2>&1
-		export_dist_f
-		# FETCH THE KEYS FOR THE CRYPTOGRAPHIC AUTHENTICATION
-		gentoo_key_f
-		# GET LATEST STAGE3 TARBALL, .DIGEST && .DIGEST.asc
-		get_latest_f
-		# VERIFY THE AUTHENTICATION OF THE DOWNLOADED FILES
-		verify_download_f
-	else
+	if [[ -n $(echo "$@" | grep '\--force-new') ]]; then
+		echo -e "\e[33mSearching for tarball...\e[0m"
 		export_dist_f
 		# GET LATEST STAGE3 TARBALL, .DIGEST && .DIGEST.asc
 		local_stage3="$(cat "${CDISTDIR}/dists/latest.info")"
@@ -343,11 +373,36 @@ fetch_new_f() {
 			# FETCH THE KEYS FOR THE CRYPTOGRAPHIC AUTHENTICATION
 			gentoo_key_f
 			# GET LATEST STAGE3 TARBALL, .DIGEST && .DIGEST.asc
-			get_latest_f
+			get_latest_f "$@"
 			# VERIFY THE AUTHENTICATION OF THE DOWNLOADED FILES
 			verify_download_f
+		fi
+	else
+		echo -e "\e[33mSearching for tarball...\e[0m"
+		if [[ -n $(echo "$@" | grep '\--fetch-new') || -n $(echo "$@" | grep '\-fn') ]]; then
+			export_dist_f
+			# FETCH THE KEYS FOR THE CRYPTOGRAPHIC AUTHENTICATION
+			gentoo_key_f
+			# GET LATEST STAGE3 TARBALL, .DIGEST && .DIGEST.asc
+			get_latest_f "$@"
+			# VERIFY THE AUTHENTICATION OF THE DOWNLOADED FILES
+			verify_download_f
+		else
+			export_dist_f
+			# GET LATEST STAGE3 TARBALL, .DIGEST && .DIGEST.asc
+			local_stage3="$(cat "${CDISTDIR}/dists/latest.info")"
+			if [[ "${local_stage3}" == "${STAGE3TB}" ]]; then
+				echo -e "[\e[32m*\e[0m] Latest stage3 is already present locally"
+			else
+				# FETCH THE KEYS FOR THE CRYPTOGRAPHIC AUTHENTICATION
+				gentoo_key_f
+				# GET LATEST STAGE3 TARBALL, .DIGEST && .DIGEST.asc
+				get_latest_f "$@"
+				# VERIFY THE AUTHENTICATION OF THE DOWNLOADED FILES
+				verify_download_f
+			fi
+		fi
 	fi
-fi
 }
 
 print_inf_f() {
@@ -373,7 +428,7 @@ case $1 in
 		echo -e "[\e[31m*\e[0m] [\e[31mERROR\e[0m: Wrong parameters"
 		exit 1;;
 	5)
-		echo -e "[\e[31m*\e[0m] Failed getting version";;
+		echo -e "[\e[31m*\e[0m] Failed Fetching version";;
 	6)
 		echo -e "[\e[31m*\e[0m] FATAL";;
 esac
@@ -473,13 +528,15 @@ pr_chroot_f() {
 			echo "${INJFLERR[@]}"
 			while true; do
 				echo "You can list the failed files again, continue, request terminal or exit"
-				read -rp "Please choose: LIST/CONTINUE/TERMINAL/EXIT" INJFLANS
+				echo "Please choose: LIST/CONTINUE/TERMINAL/EXIT"
+				read -rp "Input :: <= " INJFLANS
 				case "$INJFLANS" in
 					LIST)
 						clear; echo "${INJFLERR[@]}";;
 					CONTINUE)
 						while true; do
-							read -p "Are you sure? Y/N " YN
+							echo "Are you sure? Y/N "
+							read -p "Input :: <= " YN
 							case $YN in
 								[yY])
 									echo "Proceeding"
@@ -495,7 +552,8 @@ pr_chroot_f() {
 						INJFLESC=0;;
 					EXIT)
 						while true; do
-							read -p "Are you sure? Y/N " YN
+							echo "Are you sure? Y/N "
+							read -p "Input :: <= " YN
 							case $YN in
 								[yY])
 									echo "Aborting..."
@@ -574,7 +632,8 @@ case "$1" in
 		[[ "${CRDPENDS}" == 1 ]] && while true; do
 		echo -e "\e[33mIf you think some of those dependencies are name missmatch or not important\e[0m"
 		echo -e "\e[33mYou can choose to continue at your own ristk\e[0m"
-		read -rp "Continue? Y/N: " ANS
+		echo -e "\e[33mContinue? Y/N: "
+		read -rp "Input :: <= " ANS
 		case "${ANS}" in
 			[yY])
 				break;;
