Updated names

diff --git a/scripts/chroot_scripts/chroot_init b/scripts/chroot_scripts/chroot_init
--- a/scripts/chroot_scripts/chroot_init
+++ b/scripts/chroot_scripts/chroot_init
@@ -21,44 +21,53 @@ source "${CHDIR}/chinit.conf" \
 
 # PART C BEGINS
 if [[ -n $(echo "$@" | grep '\--force-new') ]]; then
-	part_c_f "$@" || die
+	_part_c "$@" || die
 else
 	if [[ "$(awk -F '=' '/UPDATE/{ print $2 }' <"${CHDIR}/chsinprog")" == 0 ]]; then
-		part_c_f "$@" || die
+		_part_c "$@" || die
 	else
-		if repeat_part_f "Portage Update"; then
-			part_c_f "$@" || die
+		if [[ -n $(echo "$@" | grep '\--lawful-good') && -n $(echo "$@" | grep 'gupdate') ]]; then
+			:
+		else
+			if repeat_part "Portage Update"; then
+				_part_c "$@" || die "Part C FAILED"
+			fi
 		fi
 	fi
 fi
 
 # PART PORTAGE, PROFILE AND FEATURES UPDATE
 if [[ -n $(echo "$@" | grep '\--force-new') ]]; then
-	part_portage_f "$@" && chsinit_mon_f "PORTAGE"
+	part_portage "$@" && _monitor_chroot_flow "PORTAGE" || "PORTAGE PART FAILED"
 else
 	if [[ "$(awk -F '=' '/UPDATE/{ print $2 }' <"${CHDIR}/chsinprog")" == 0 ]]; then
-		part_portage_f "$@" && chsinit_mon_f "PORTAGE"
+		part_portage "$@" && _monitor_chroot_flow "PORTAGE" || "PORTAGE PART FAILED"
 	else
-		if repeat_part_f "Portage Configuration"; then
-			part_portage_f "$@" && chsinit_mon_f "PORTAGE"
+		if [[ -n $(echo "$@" | grep '\--lawful-good') && -n $(echo "$@" | grep 'gportage') ]]; then
+			:
+		else
+			if repeat_part "Portage Configuration"; then
+				part_portage "$@" && _monitor_chroot_flow "PORTAGE" || "PORTAGE PART FAILED"
+			fi
 		fi
 	fi
 fi
 
-# APPLY NEW CHANGES
-apply_new_f "UDN"
-
 if [[ -n $(echo "$@" | grep '\--force-new') ]]; then
 	:
 else
-	if [[ -n $(echo "$@" | grep 'precomp') ]]; then
-		# Part D Begins
-		if [[ "$(awk -F '=' '/REBUILD/{ print $2 }' <"${CHDIR}/chsinprog")" == 0 ]]; then
-			echo -e "\e[35mPart D: Rebuilding system\e[0m"
-			env-update > /dev/null 2>&1 && source /etc/profile && export PS1="( 'Part D: Rebuilding system' ) $PS1"
-			export PATH=${PATH}:${CHDIR}
-			emerge_rebuild_system_f
-			chsinit_mon_f "REBUILD"
+	if [[ -n $(echo "$@" | grep '\--lawful-good') && -n $(echo "$@" | grep 'grebuild') ]]; then
+		:
+	else
+		if [[ -n $(echo "$@" | grep 'precomp') ]]; then
+			# Part D Begins
+			if [[ "$(awk -F '=' '/REBUILD/{ print $2 }' <"${CHDIR}/chsinprog")" == 0 ]]; then
+				echo -e "\e[35mPart D: Rebuilding system\e[0m"
+				env-update > /dev/null 2>&1 && source /etc/profile && export PS1="( 'Part D: Rebuilding system' ) $PS1"
+				export PATH=${PATH}:${CHDIR}
+				build_the_world
+				chsinit_mon_f "REBUILD"
+			fi
 		fi
 	fi
 fi
@@ -70,21 +79,29 @@ else
 	if [[ "$(awk -F '=' '/CONFIGURE/{ print $2 }' <"${CHDIR}/chsinprog")" == 0 ]]; then
 		configure_system_f
 	else
-		if repeat_part_f "System Configuration"; then
-			configure_system_f
+		if [[ -n $(echo "$@" | grep '\--lawful-good') && -n $(echo "$@" | grep 'gconfigure') ]]; then
+			:
+		else
+			if repeat_part "System Configuration"; then
+				configure_system_f
+			fi
 		fi
 	fi
 fi
 
 # PART F BEGINS
 if [[ -n $(echo "$@" | grep '\--force-new') ]]; then
-	inst_req_f
+	emerge_requested
 else
 	if [[ "$(awk -F '=' '/INSTALL/{ print $2 }' <"${CHDIR}/chsinprog")" == 0 ]]; then
-		inst_req_f
+		emerge_requested
 	else
-		if repeat_part_f "Installing Packages"; then
-			inst_req_f
+		if [[ -n $(echo "$@" | grep '\--lawful-good') && -n $(echo "$@" | grep 'ginstall') ]]; then
+			:
+		else
+			if repeat_part "Installing Packages"; then
+				emerge_requested
+			fi
 		fi
 	fi
 	unset YN
@@ -92,48 +109,64 @@ fi
 
 # PART G BEGINS
 if [[ -n $(echo "$@" | grep '\--force-new') ]]; then
-	runlevel_f
+	_runlevel_configuration
 else
 	if [[ "$(awk -F '=' '/RUNLEVEL/{ print $2 }' <"${CHDIR}/chsinprog")" == 0 ]]; then
-		runlevel_f
+		_runlevel_configuration
 	else
-		if repeat_part_f "Runlevel Configuration"; then
-			runlevel_f
+		if [[ -n $(echo "$@" | grep '\--lawful-good') && -n $(echo "$@" | grep 'grun') ]]; then
+			:
+		else
+			if repeat_part "Runlevel Configuration"; then
+				_runlevel_configuration
+			fi
 		fi
 	fi
 	unset YN
 fi
 
 # PART H BEGINS
-if [[ -n $(echo "$@" | grep '\--force-new') ]]; then
-	echo -e "The \e[34mBuilding kernel\e[0m"
-	genkernel --install kernel --menuconfig --kernel-config="${CHDIR}/kernel-conf" \
-	--makeopts="-j${MKPS}" --btrfs --postclear --e2fsprogs
-	echo -e "The \e[34mkernel\e[0m built was \e[32msuccessful\e[0m"
-	chsinit_mon_f "KERNEL"
-else
-	if [[ "$(awk -F '=' '/KERNEL/{ print $2 }' <"${CHDIR}/chsinprog")" == 0 ]]; then
-		kernel_conf_f
+if [[ -z $(echo "$@" | grep '\--no-kernel') ]]; then
+	if [[ -n $(echo "$@" | grep '\--force-new') ]]; then
+		_kernel_build "$@"
 	else
-		if repeat_part_f "Kernel Configuration"; then
-			kernel_conf_f
+		if [[ "$(awk -F '=' '/KERNEL/{ print $2 }' <"${CHDIR}/chsinprog")" == 0 ]]; then
+			_kernel_build
+		else
+			if [[ -n $(echo "$@" | grep '\--lawful-good') && -n $(echo "$@" | grep 'gkernel') ]]; then
+				:
+			else
+				if repeat_part "Kernel Configuration"; then
+					_kernel_build
+				fi
+			fi
 		fi
+		unset YN
 	fi
-	unset YN
+else
+	:
 fi
 
 # PART I BEGINS
-if [[ -n $(echo "$@" | grep '\--force-new') ]]; then
-	initramfs_f
-else
-	if [[ "$(awk -F '=' '/INITRAMFS/{ print $2 }' <"${CHDIR}/chsinprog")" == 0 ]]; then
-		initramfs_f
+if [[ -z $(echo "$@" | grep '\--no-kernel') && -z $(echo "$@" | grep '\--no-initramfs') ]]; then
+	if [[ -n $(echo "$@" | grep '\--force-new') ]]; then
+		_initramfs_builder
 	else
-		if repeat_part_f "Initramfs Configuration"; then
-			initramfs_f
+		if [[ "$(awk -F '=' '/INITRAMFS/{ print $2 }' <"${CHDIR}/chsinprog")" == 0 ]]; then
+			_initramfs_builder
+		else
+			if [[ -n $(echo "$@" | grep '\--lawful-good') && -n $(echo "$@" | grep 'ginitrd') ]]; then
+				:
+			else
+				if repeat_part "Initramfs Configuration"; then
+					_initramfs_builder
+				fi
+			fi
 		fi
+		unset YN
 	fi
-	unset YN
+else
+	:
 fi
 
 #emerge --deselect gentoo-sources
diff --git a/scripts/functions/init_stage3_seq b/scripts/functions/init_stage3_seq
--- a/scripts/functions/init_stage3_seq
+++ b/scripts/functions/init_stage3_seq
@@ -11,13 +11,13 @@ LC_CTYPE="en_US.UTF-8"
 source "${CWORKDIR}/scripts/functions/catalyst_functions" || die "Missing scripts"
 
 # EXPORT THE DIRECTORIES DEFINED BY STAGE1.SPEC
-export_cat_dirs_f
+_export_catalyst_workdirs
 
 # CREATE DIRECTORIES FOR CATALYST
-create_cata_dirs_f
+_create_catalyst_workdirs
 
 # CHECK IF STAGE3 TARBALL IS PRESENT AT THE INDICATED DIRECTORY
-tar_path_name_f "1"
+_target_paths "1"
 
 if [[ ! -e "${CATDIR}/builds/${TARGETPATH}/${TARGETNAME}.tar.bz2" ]]; then
 	cp "${CDISTDIR}/dists/stage3-${ARCH}-latest.tar.bz2" "${CATDIR}/builds/${TARGETPATH}/${TARGETNAME}.tar.bz2"
@@ -25,22 +25,22 @@ fi
 
 # CHECK IF SNAPSHOT EXISTS AND HAS NORMAL SIZE
 check_portage_snap_f() {
-if [[ ! -e "${CATDIR}/snapshots/portage-${SNAPSHOTNAME}.tar.bz2" ]] || ! chk_snap_f "${CATDIR}/snapshots/portage-${SNAPSHOTNAME}.tar.bz2"; then
+if [[ ! -e "${CATDIR}/snapshots/portage-${SNAPSHOTNAME}.tar.bz2" ]] || ! _snapshot_checkup "${CATDIR}/snapshots/portage-${SNAPSHOTNAME}.tar.bz2"; then
 # REMOVE THE SNAPSHOT IF IT EXISTS BUT SEEMS HEAVILY MODIFIED
 rm -f "${CATDIR}/snapshots/portage-${SNAPSHOTNAME}.tar.bz2" >/dev/null 2>&1
 while true; do
-	opt_f
+	_copt
 	echo -e "[\e[31m*\e[0m] Could not locate snapshots/portage-${SNAPSHOTNAME}.tar.bz2 @ ${CATDIR}/snapshots"
 	echo "Please select an option"
 	read -rp "Input :: <= " ANS
 	case "$ANS" in
 		I|i|1)
-			get_latest_portage_f "$@" && BRKVAR=0 || BRKVAR=1
+			_get_latest_snapshot "$@" && BRKVAR=0 || BRKVAR=1
 			;;
 		II|ii|2)
 			echo "Please enter the absolute path with the snapshot included: "
 			read -rp "Input :: <= " PATHTOSNAP
-			if [[ -n "${PATHTOSNAP}" ]] && chk_snap_f "${PATHTOSNAP}"; then
+			if [[ -n "${PATHTOSNAP}" ]] && _snapshot_checkup "${PATHTOSNAP}"; then
 				cp "${PATHTOSNAP}" "${CATDIR}/snapshots/portage-${SNAPSHOTNAME}.tar.bz2" \
 				&& echo -e "\e[34mCopying snapshot to ${CATDIR}/snapshots\e[0m" && BRKVAR=0 || BTWRK=1				
 			else
@@ -65,9 +65,9 @@ while true; do
 			break;;
 		III|iii|3)
 			echo -e "\e[32mSearching\e[0m..."
-			search_snap_f && echo -e "\e[32mChecking\e[0m..." || { echo -e "\e[31mCould not locate the snapshot\e[0m"; BRKVAR=1; }
+			_search_snapshot && echo -e "\e[32mChecking\e[0m..." || { echo -e "\e[31mCould not locate the snapshot\e[0m"; BRKVAR=1; }
 			echo -e "[\e[32m*\e[0m]  Located the snapshot"
-			if chk_snap_f "${CATDIR}/snapshots/portage-${SNAPSHOTNAME}.tar.bz2"; then
+			if _snapshot_checkup "${CATDIR}/snapshots/portage-${SNAPSHOTNAME}.tar.bz2"; then
 				echo -e "[\e[32m*\e[0m]  Snapshot seems normal"
 				BRKVAR=0
 			else
@@ -90,10 +90,10 @@ while true; do
 			;;
 		IV|iv|4)
 			echo "\e[35mOpening new shell, please copy your snapshot to ${CATDIR}/snapshots with name: portage-${SNAPSHOTNAME}.tar.bz2\e[0m"
-			subterm_f
+			_csubshell
 			if [[ -e "${CATDIR}/snapshots/portage-${SNAPSHOTNAME}.tar.bz2" ]]; then
 				echo -e "\e[32mChecking\e[0m..."
-				if chk_snap_f "${CATDIR}/snapshots/portage-${SNAPSHOTNAME}.tar.bz2"; then
+				if _snapshot_checkup "${CATDIR}/snapshots/portage-${SNAPSHOTNAME}.tar.bz2"; then
 					echo -e "[\e[32m*\e[0m]  Snapshot seems normal"
 					BRKVAR=0
 				else
@@ -127,7 +127,7 @@ while true; do
 					read -rp "Input :: <= " YN
 					case "${YN:-n}" in
 						[yY][eE][sS]|[yY])
-							build_port && echo -e "[\e[32m*\e[0m] Built" || echo -e "[\e[31m*\e[0m] Failed"
+							_snapshot_builder && echo -e "[\e[32m*\e[0m] Built" || echo -e "[\e[31m*\e[0m] Failed"
 							;;
 						[nN][oO]|[nN])
 							while true; do
@@ -145,7 +145,7 @@ while true; do
 												case $YN in
 													[yY][eE][sS]|[yY])
 														export CATPORTDIR
-														build_port && echo -e "[\e[32m*\e[0m] Built" || echo -e "[\e[31m*\e[0m] Failed"
+														_snapshot_builder && echo -e "[\e[32m*\e[0m] Built" || echo -e "[\e[31m*\e[0m] Failed"
 														;;
 													[nN][oO]|[nN])
 														echo -e "[\e[31m*\e[0m] Returning back to options"
@@ -154,7 +154,7 @@ while true; do
 												esac
 											done
 										else
-											build_port && echo -e "[\e[32m*\e[0m] Built" || echo -e "[\e[31m*\e[0m] Failed"
+											_snapshot_builder && echo -e "[\e[32m*\e[0m] Built" || echo -e "[\e[31m*\e[0m] Failed"
 										fi
 										break;;
 									[nN][oO]|[nN])
@@ -167,7 +167,7 @@ while true; do
 					esac
 				done
 			else
-				build_port && echo -e "[\e[32m*\e[0m] Built" || echo -e "[\e[31m*\e[0m] Failed"
+				_snapshot_builder && echo -e "[\e[32m*\e[0m] Built" || echo -e "[\e[31m*\e[0m] Failed"
 			fi
 			;;
 	esac
@@ -186,7 +186,7 @@ if [[ -n $(echo $@ | grep '\--force-new') ]]; then
 	if [[ ! -e "${CATDIR}/snapshots/portage-${SNAPSHOTNAME}.tar.bz2" ]]; then
 		echo -e "\e[33mCould not locate snapshot\e[0m"
 		echo -e "\e[33mAttempting to fetch new...\e[0m"
-		get_latest_portage_f "$@" \
+		_get_latest_snapshot "$@" \
 		|| { echo -e "\e[34mCreating snapshot...\e[0m"
 		catalyst -s "${SNAPSHOTNAME}" && pass || die "FAILED"; }
 	fi
@@ -195,23 +195,23 @@ else
 fi
 
 # STAGE 1
-check_then_call_stageX_f "${CATDIR}/builds/${TARGETPATH}/${TARGETNAME}.tar.bz2" "1" "$@"
+_call_stagex_f "${CATDIR}/builds/${TARGETPATH}/${TARGETNAME}.tar.bz2" "1" "$@"
 unset TARGETNAME
 unset TARGETPATH
 unset TARGETSTAMP
 unset SNAPSHOTNAME
-tar_path_name_f "2"
+_target_paths "2"
 
 # STAGE 2
-check_then_call_stageX_f "${CATDIR}/builds/${TARGETPATH}/stage1-${ARCH}-${TARGETSTAMP}.tar.bz2" "2" "$@"
+_call_stagex_f "${CATDIR}/builds/${TARGETPATH}/stage1-${ARCH}-${TARGETSTAMP}.tar.bz2" "2" "$@"
 unset TARGETNAME
 unset TARGETPATH
 unset TARGETSTAMP
 unset SNAPSHOTNAME
-tar_path_name_f "3"
+_target_paths "3"
 
 # STAGE 3
-check_then_call_stageX_f "${CATDIR}/builds/${TARGETPATH}/stage2-${ARCH}-${TARGETSTAMP}.tar.bz2" "3" "$@"
+_call_stagex_f "${CATDIR}/builds/${TARGETPATH}/stage2-${ARCH}-${TARGETSTAMP}.tar.bz2" "3" "$@"
 unset ANS
 unset TARGETNAME
 unset TARGETPATH
diff --git a/scripts/sinit b/scripts/sinit
--- a/scripts/sinit
+++ b/scripts/sinit
@@ -17,28 +17,49 @@ part_a_f() {
 case "$2" in
 	catalyst)
 		# PART A FUNDAMENTALS
-		fundamentals_f "${CDISTDIR}/workdir-catalyst" "$@"
-		if [[ -n $(echo "$@" | grep 'seed') ]]; then
-			fetch_new_f "$@" || { print_inf_f 2 && exit; }
+		if [[ -n $(echo "$@" | grep '\--lawful-good') && -n $(echo "$@" | grep 'gfund') ]]; then
+			:
+		else
+			fundamentals_f "${CDISTDIR}/workdir-catalyst" "$@"
 		fi
+
+		if [[ -n $(echo "$@" | grep 'seed') ]]; then
+			fetch_new_f "$@" || die "FAILED"
+		fi
+		
 		if [[ "$(awk -F '=' '/CATALYST/{ print $2 }' <"${CLOCALLG}/sinprog")" == 0 ]]; then
-			calling_catalyst_f "$@" || exit 1
+			calling_catalyst_f "$@" || die
 		else
-			repeat_sub_part_f "Catalyst" "configured" \
-			&& [[ "$?" == 0 ]] && { calling_catalyst_f "$@" || exit 1; } \
-			|| echo -e "\e[33mProceeding with extraction...\e[0m"
-		fi \
-		&& [[ "$?" == 0 || "$?" == 9 ]] \
-		&& if [[ "$(awk -F '=' '/EXTRACTION/{ print $2 }' <"${CLOCALLG}/sinprog")" == 0 ]]; then
-			catalyst_extr_tar_f "$@" || exit 1
+			if [[ -n $(echo "$@" | grep '\--lawful-good') && -n $(echo "$@" | grep 'gcat') ]]; then
+				:
+			else
+				if repeat_sub_part_f "Catalyst" "configured"; then
+					calling_catalyst_f "$@" || die
+				else	
+					echo -e "\e[33mProceeding with extraction...\e[0m"
+				fi
+			fi
+		fi
+
+		
+		if [[ "$(awk -F '=' '/EXTRACTION/{ print $2 }' <"${CLOCALLG}/sinprog")" == 0 ]]; then
+			catalyst_extr_tar_f "$@" && RPSRVAR=0 || die
 		else
-			repeat_sub_part_f "Extraction" "completed" \
-			&& [[ "$?" == 0 ]] && { catalyst_extr_tar_f "$@" || exit 1; } \
-			|| echo -e "\e[33mProceeding to Part: B...\e[0m"
-		fi \
-		&& [[ "$?" == 0 || "$?" == 9 ]] \
-		&& export BWORKDIR="${CDISTDIR}/workdir-catalyst" \
-		&& PARTBCOND="0"
+			if [[ -n $(echo "$@" | grep '\--lawful-good') && -n $(echo "$@" | grep 'gextr') ]]; then
+				:
+			else
+				if repeat_sub_part_f "Extraction" "completed"; then
+					catalyst_extr_tar_f "$@" && RPSRVAR=0 || die
+				else
+					echo -e "\e[33mProceeding to Part: B...\e[0m"
+				fi
+			fi
+		fi
+
+		if [[ "$RPSRVAR" == 0 || "$RPSRVAR" == 9 ]]; then
+			export BWORKDIR="${CDISTDIR}/workdir-catalyst" \
+			&& PARTBCOND="0"
+		fi
 		unset CATDIR
 		unset TARGETNAME
 		unset TARGETPATH
@@ -48,42 +69,58 @@ case "$2" in
 		# PART A FUNDAMENTALS
 		fundamentals_f "${CDISTDIR}/workdir-precomp" "$@"
 		if [[ -n $(echo "$@" | grep 'seed') ]]; then
-			fetch_new_f "$@" || { print_inf_f 2 && exit; }
+			fetch_new_f "$@" || die "Failed"
 		fi
 		if [[ "$(awk -F '=' '/PRECOMP/{ print $2 }' <"${CLOCALLG}/sinprog")" == 0 ]]; then
 			check_dir_f "${CDISTDIR}/dists/stage3-${ARCH}-latest.tar.bz2" \
-			"${CDISTDIR}/workdir-precomp" "$@" || exit 1
+			"${CDISTDIR}/workdir-precomp" "$@" && RPSRVAR=0 || die
 		else
-			repeat_sub_part_f "Precomp Extraction" "completed" && { check_dir_f \
-			"${CDISTDIR}/dists/stage3-${ARCH}-latest.tar.bz2" \
-			"${CDISTDIR}/workdir-precomp" "$@" || exit 1; }
-		fi \
-		&& [[ "$?" == 0 || "$?" == 9 ]] \
-		&& export BWORKDIR="${CDISTDIR}/workdir-precomp" \
-		&& PARTBCOND="0" \
-		&& sinit_mon_f "PRECOMP"
-		;;
+			if [[ -n $(echo "$@" | grep '\--lawful-good') && -n $(echo "$@" | grep 'gprec') ]]; then
+				:
+			else
+				if repeat_sub_part_f "Precomp Extraction" "completed"; then
+					check_dir_f
+					"${CDISTDIR}/dists/stage3-${ARCH}-latest.tar.bz2" \
+					"${CDISTDIR}/workdir-precomp" "$@" && RPSRVAR=0
+				else
+					die
+				fi
+			fi
+		fi
+
+		if [[ "$RPSRVAR" == 0 || "$RPSRVAR" == 9 ]]; then
+			export BWORKDIR="${CDISTDIR}/workdir-precomp" \
+			&& PARTBCOND="0" \
+			&& sinit_mon_f "PRECOMP"
+		fi;;
 esac
 }
 
+echo $@
 if [[ -n $(echo "$@" | grep '\--force-new') ]]; then
 	part_a_f "$@"
 else
-	if [[ "$(awk -F '=' '/PARTA/{ print $2 }' <"${CLOCALLG}/sinprog")" == 1 ]]; then
-		repeat_part_f "A" && part_a_f "$@"
-
-		[[ "$?" == 0 || "$?" == 9 ]] \
-		&& if [[ -n $(echo "$@" | grep 'catalyst') ]]; then
-			export BWORKDIR="${CDISTDIR}/workdir-catalyst" \
-			&& PARTBCOND="0"
-		elif [[ -n $(echo "$@" | grep 'precomp') ]]; then
-			export BWORKDIR="${CDISTDIR}/workdir-precomp" \
-			&& PARTBCOND="0"
-		fi \
-		|| { echo -e "\e[31mNo workdir defined. Wont proceed!\e[0m" \
-		&& echo "$@" && exit 1; }
+	if [[ -n $(echo "$@" | grep '\--lawful-good') && -n $(echo "$@" | grep 'gparta') ]]; then
+		:
 	else
-		part_a_f "$@"
+		if [[ "$(awk -F '=' '/PARTA/{ print $2 }' <"${CLOCALLG}/sinprog")" == 1 ]]; then
+			repeat_part_f "A" && part_a_f "$@"
+			
+			if [[ "$RPPVAR" == 9 ]]; then
+				if [[ -n $(echo "$@" | grep 'catalyst') ]]; then
+					export BWORKDIR="${CDISTDIR}/workdir-catalyst" \
+					&& PARTBCOND="0"
+				elif [[ -n $(echo "$@" | grep 'precomp') ]]; then
+					export BWORKDIR="${CDISTDIR}/workdir-precomp" \
+					&& PARTBCOND="0"
+				fi
+			else
+				echo -e "\e[31mNo workdir defined. Wont proceed!\e[0m"
+				die "$@"
+			fi
+		else
+			part_a_f "$@"
+		fi
 	fi
 fi
 
@@ -108,7 +145,7 @@ TARGETSTAMP="$(grep 'version_stamp' "${CCONFDIR}/system/catalyst/stage3.spec" \
 			tar cvf "${CDISTDIR}/stage3-amd64-${GSEVER}.tar.bz2" -C "${BWORKDIR}" >/dev/null 2>&1 \
 			&& { print_inf 1 && echo -e "\e[34mYou can find your system @ ${CDISTDIR}\e[0m"
 			echo -e "\e[34mWith version extension: ${GSEVER}\e[0m"; } \
-			|| { print_inf 2; exit 1; }
+			|| die "Failed"
 			break
 		else
 			((++SUBBUILD))
