Switched to die instead of custom messages

diff --git a/scripts/chroot_scripts/chroot_init b/scripts/chroot_scripts/chroot_init
--- a/scripts/chroot_scripts/chroot_init
+++ b/scripts/chroot_scripts/chroot_init
@@ -15,36 +15,40 @@ source /etc/profile && export PS1="( 'Part C: Preparing to bootstrap' ) $PS1"
 export CHDIR="/sinit.d"
 export PATH=${PATH}:${CHDIR}
 source "${CHDIR}/chinit.conf" \
-&& source "${CHDIR}/cfunctions" && source "${CHDIR}/coptions"|| { chprint_inf_f 2; exit 1; }
+&& source "${CHDIR}/cfunctions" && source "${CHDIR}/coptions"|| die "Failed"
 [[ ! -e "${CHDIR}/emergeresume" ]] && echo "#####" >> "${CHDIR}/emergeresume" \
 || sed -i "/#####/d" "${CHDIR}/emergeresume"
 
 # PART C BEGINS
-if [[ -n $(echo $@ | grep '\--force-new') ]]; then
-	part_c_f "$@" || exit 1
+if [[ -n $(echo "$@" | grep '\--force-new') ]]; then
+	part_c_f "$@" || die
 else
 	if [[ "$(awk -F '=' '/UPDATE/{ print $2 }' <"${CHDIR}/chsinprog")" == 0 ]]; then
-		part_c_f "$@" || exit 1
+		part_c_f "$@" || die
 	else
-		repeat_part_f "Portage Update" "part_c_f $@"
+		if repeat_part_f "Portage Update"; then
+			part_c_f "$@" || die
+		fi
 	fi
 fi
 
 # PART PORTAGE, PROFILE AND FEATURES UPDATE
-if [[ -n $(echo $@ | grep '\--force-new') ]]; then
+if [[ -n $(echo "$@" | grep '\--force-new') ]]; then
 	part_portage_f "$@" && chsinit_mon_f "PORTAGE"
 else
 	if [[ "$(awk -F '=' '/UPDATE/{ print $2 }' <"${CHDIR}/chsinprog")" == 0 ]]; then
 		part_portage_f "$@" && chsinit_mon_f "PORTAGE"
 	else
-		repeat_part_f "Portage Configuration" "part_portage_f $@"
+		if repeat_part_f "Portage Configuration"; then
+			part_portage_f "$@" && chsinit_mon_f "PORTAGE"
+		fi
 	fi
 fi
 
 # APPLY NEW CHANGES
 apply_new_f "UDN"
 
-if [[ -n $(echo $@ | grep '\--force-new') ]]; then
+if [[ -n $(echo "$@" | grep '\--force-new') ]]; then
 	:
 else
 	if [[ -n $(echo "$@" | grep 'precomp') ]]; then
@@ -60,42 +64,48 @@ else
 fi
 
 # PART E BEGINS
-if [[ -n $(echo $@ | grep '\--force-new') ]]; then
+if [[ -n $(echo "$@" | grep '\--force-new') ]]; then
 	configure_system_f
 else
 	if [[ "$(awk -F '=' '/CONFIGURE/{ print $2 }' <"${CHDIR}/chsinprog")" == 0 ]]; then
 		configure_system_f
 	else
-		repeat_part_f "System Configuration" "configure_system_f"
+		if repeat_part_f "System Configuration"; then
+			configure_system_f
+		fi
 	fi
 fi
 
 # PART F BEGINS
-if [[ -n $(echo $@ | grep '\--force-new') ]]; then
+if [[ -n $(echo "$@" | grep '\--force-new') ]]; then
 	inst_req_f
 else
 	if [[ "$(awk -F '=' '/INSTALL/{ print $2 }' <"${CHDIR}/chsinprog")" == 0 ]]; then
 		inst_req_f
 	else
-		repeat_part_f "Installing Packages" "inst_req_f"
+		if repeat_part_f "Installing Packages"; then
+			inst_req_f
+		fi
 	fi
 	unset YN
 fi
 
 # PART G BEGINS
-if [[ -n $(echo $@ | grep '\--force-new') ]]; then
+if [[ -n $(echo "$@" | grep '\--force-new') ]]; then
 	runlevel_f
 else
 	if [[ "$(awk -F '=' '/RUNLEVEL/{ print $2 }' <"${CHDIR}/chsinprog")" == 0 ]]; then
 		runlevel_f
 	else
-		repeat_part_f "Runlevel Configuration" "runlevel_f"
+		if repeat_part_f "Runlevel Configuration"; then
+			runlevel_f
+		fi
 	fi
 	unset YN
 fi
 
 # PART H BEGINS
-if [[ -n $(echo $@ | grep '\--force-new') ]]; then
+if [[ -n $(echo "$@" | grep '\--force-new') ]]; then
 	echo -e "The \e[34mBuilding kernel\e[0m"
 	genkernel --install kernel --menuconfig --kernel-config="${CHDIR}/kernel-conf" \
 	--makeopts="-j${MKPS}" --btrfs --postclear --e2fsprogs
@@ -105,19 +115,23 @@ else
 	if [[ "$(awk -F '=' '/KERNEL/{ print $2 }' <"${CHDIR}/chsinprog")" == 0 ]]; then
 		kernel_conf_f
 	else
-		repeat_part_f "Kernel Configuration" "kernel_conf_f"
+		if repeat_part_f "Kernel Configuration"; then
+			kernel_conf_f
+		fi
 	fi
 	unset YN
 fi
 
 # PART I BEGINS
-if [[ -n $(echo $@ | grep '\--force-new') ]]; then
+if [[ -n $(echo "$@" | grep '\--force-new') ]]; then
 	initramfs_f
 else
 	if [[ "$(awk -F '=' '/INITRAMFS/{ print $2 }' <"${CHDIR}/chsinprog")" == 0 ]]; then
 		initramfs_f
 	else
-		repeat_part_f "Initramfs Configuration" "initramfs_f"
+		if repeat_part_f "Initramfs Configuration"; then
+			initramfs_f
+		fi
 	fi
 	unset YN
 fi
@@ -127,6 +141,7 @@ fi
 #eclean-dist -d
 #rm -rf /usr/src/linux-4.9.16-gentoo
 #rm -rf /usr/src/linux
+#rm -rf issues.info
 
 # Creating user-data dir-tree
 mkdir -p /user-data/persistent/{etc,var,logs,config.d,local,rmount}
diff --git a/scripts/functions/catalyst_functions b/scripts/functions/catalyst_functions
--- a/scripts/functions/catalyst_functions
+++ b/scripts/functions/catalyst_functions
@@ -136,7 +136,7 @@ fi
 	echo -e "[\e[32m*\e[0m] \e[34mFetchinglatest portage snapshot\e[0m" \
 	&& wget -O "${CATDIR}/portage-latest.tar.bz2" \
 	http://distfiles.gentoo.org/snapshots/portage-latest.tar.bz2 >/dev/null 2>&1 \
-	&& print_inf 1 && return 0 || { print_inf 2; return 1; } 
+	&& pass && return 0 || die "Failed" 
 }
 
 verify_portage_f() {
@@ -158,7 +158,7 @@ simple_fetch_f() {
 	echo -e "[\e[32m*\e[0m] \e[34mFetching latest portage snapshot\e[0m" \
 	&& wget -O "${CATDIR}/portage-latest.tar.bz2" \
 	http://distfiles.gentoo.org/snapshots/portage-latest.tar.bz2 >/dev/null 2>&1 \
-	&& print_inf 1 && return 0 || { print_inf 2; return 1; }
+	&& pass && return 0 || die "Failed"
 }
 
 get_latest_portage_f() {
@@ -171,7 +171,7 @@ get_latest_portage_f() {
 		simple_fetch_f
 	else
 		if [[ -n $(echo "$@" | grep '\--fetch-new') || -n $(echo "$@" | grep '\-fn') ]]; then
-			[[ -z "$@" ]] && print_inf 4 && exit 1
+			[[ -z "$@" ]] && die "Wrong parameters"
 			export_cat_dirs_f
 			rm -f "${CATDIR}/portage-latest.tar.bz2"
 			rm -f "${CATDIR}/portage-latest.tar.bz2.md5sum"
@@ -187,7 +187,7 @@ get_latest_portage_f() {
 					echo "Copying to ${CATDIR}/snapshots" \
 					&& cp "${CATDIR}/portage-latest.tar.bz2" "${CATDIR}/snapshots/portage-${SNAPSHOTNAME}.tar.bz2" \
 					&& cp "${CATDIR}/portage-latest.tar.bz2.md5sum" "${CATDIR}/snapshots/portage-${SNAPSHOTNAME}.tar.bz2.md5sum" \
-					&& print_inf 1 && return 0 || { print_inf 2; return 1; }
+					&& pass && return 0 || die "Failed"
 				else
 					echo -e "[\e[31m*\e[0m] \e[31mFAILD\e[0m: Snapshot \e[31mverified\e[0m"
 					fetch_portage_f \
@@ -195,10 +195,10 @@ get_latest_portage_f() {
 					&& echo "Copying to ${CATDIR}/snapshots" \
 					&& cp "${CATDIR}/portage-latest.tar.bz2" "${CATDIR}/snapshots/portage-${SNAPSHOTNAME}.tar.bz2" \
 					&& cp "${CATDIR}/portage-latest.tar.bz2.md5sum" "${CATDIR}/snapshots/portage-${SNAPSHOTNAME}.tar.bz2.md5sum" \
-					&& print_inf 1 && return 0 || { print_inf 2; return 1; }
+					&& pass && return 0 || die "Failed"
 				fi
 			else
-				print_inf 1 && return 0 || { print_inf 2; return 1; }
+				die "Failed"
 			fi
 		fi
 	fi
@@ -206,7 +206,7 @@ get_latest_portage_f() {
 
 # CHECK SNAPSHOT
 chk_snap_f() {
-[[ -z "$@" ]] && print_inf 4 && return 1
+[[ -z "$@" ]] && die "Wrong parameters"
 [[ $(du -sh "$1" | awk -F ' ' '{print $1}' | sed 's/[^0-9]*//g') -le 220 ]] \
 && [[ $(du -sh "$1" | awk -F ' ' '{print $1}' | sed 's/[^0-9]*//g') -ge 50 ]] \
 || return 1
@@ -248,7 +248,7 @@ unset ARRAYSNAP
 }
 
 stageX_f() {
-	[[ -z "$@" ]] && print_inf 4 && return 1
+	[[ -z "$@" ]] && die "Wrong parameters"
 	if [[ -e "$1" ]]; then
 		# STAGE 2
 		echo -e "\e[35mBuilding stage$2\e[0m"
@@ -257,7 +257,7 @@ stageX_f() {
 		> "${CATDIR}/.stage$2.spec"
 
 		catalyst -c "${CCONFDIR}/system/catalyst/catalyst.conf" -f "${CATDIR}/.stage$2.spec" \
-		&& print_inf 1 || { print_inf 2 && exit 1; }
+		&& pass || die "Failed"
 	else
 		echo -e "\e[31mCould not locate stage$2-${ARCH}-${TARGETSTAMP}.tar.bz2\e[0m"
 		return 1
@@ -265,10 +265,10 @@ stageX_f() {
 }
 
 check_then_call_stageX_f() {
-	[[ -z "$@" ]] && print_inf 4 && return 1
+	[[ -z "$@" ]] && die "Wrong parameters"
 	if [[ -n $(echo $@ | grep '\--force-new') ]]; then
 		echo -e "\e[31mForce new is active!\e[0m"
-		#stageX_f "$1" "$2"
+		stageX_f "$1" "$2"
 	else
 		if [[ -e "${CATDIR}/builds/${TARGETPATH}/stage$2-${ARCH}-${TARGETSTAMP}.tar.bz2" && -n $(echo "$@" | grep "s$2") ]]; then
 
diff --git a/scripts/functions/init_stage3_seq b/scripts/functions/init_stage3_seq
--- a/scripts/functions/init_stage3_seq
+++ b/scripts/functions/init_stage3_seq
@@ -6,9 +6,9 @@ LC_ALL="en_US.UTF-8"
 LC_CTYPE="en_US.UTF-8"
 
 # PP CHECK
-[[ -z "$@" ]] && print_inf_f 4 && exit 1
+[[ -z "$@" ]] && print_inf_f
 
-source "${CWORKDIR}/scripts/functions/catalyst_functions" || { echo -e "\e[32mMissing scripts\e[0m" && exit 1; }
+source "${CWORKDIR}/scripts/functions/catalyst_functions" || die "Missing scripts"
 
 # EXPORT THE DIRECTORIES DEFINED BY STAGE1.SPEC
 export_cat_dirs_f
@@ -181,11 +181,14 @@ unset BRKVAR
 }
 
 if [[ -n $(echo $@ | grep '\--force-new') ]]; then
+	echo -e "\e[33mSearching for portage snapshot...\e[0m"
 	echo -e "\e[31mForce new is active!\e[0m"
 	if [[ ! -e "${CATDIR}/snapshots/portage-${SNAPSHOTNAME}.tar.bz2" ]]; then
+		echo -e "\e[33mCould not locate snapshot\e[0m"
+		echo -e "\e[33mAttempting to fetch new...\e[0m"
 		get_latest_portage_f "$@" \
 		|| { echo -e "\e[34mCreating snapshot...\e[0m"
-		catalyst -s "${SNAPSHOTNAME}" && print_inf 1 || { print_inf 2 && exit 1; }; }
+		catalyst -s "${SNAPSHOTNAME}" && pass || die "FAILED"; }
 	fi
 else
 	check_portage_snap_f
diff --git a/scripts/functions/sinit_functions b/scripts/functions/sinit_functions
--- a/scripts/functions/sinit_functions
+++ b/scripts/functions/sinit_functions
@@ -12,6 +12,28 @@ subshel_f() {
 	echo -e "\e[33mYou are back to parent\e[0m"
 }
 
+die() {
+	echo "$@" 1>&2 ; exit 1
+}
+
+pass() {
+	echo echo -e "[\e[34mDone\e[0m]"
+}
+
+print_inf_f() {
+	clear
+	echo -e "[\e[31mFATAL\e[0m]"
+	echo -e "\e[31mIf this message is printed while using the Maim Menu\e[0m"
+	echo -e "\e[31mThat means essential files are altered or something bad is happening.\e[0m"
+	echo
+	echo -e "\e[31mPlease run a health-check from the ~Main Menu~ and a Version check first.\e[0m"
+	echo -e "\e[31mIf you see this again after the health/version check, please submit a bug report\e[0m"
+	echo -e "\e[31mand stop using the program, or data loss may occur.\e[0m"
+	echo
+	echo -e "\e[31mExiting...\e[0m"
+	exit 1
+}
+
 repeat_part_f() {
 while true; do
 	echo -e "\e[33mPart $1: Has been completed\e[0m"
@@ -58,7 +80,7 @@ help_f() {
 calling_catalyst_f(){
 	echo -e "\e[34mCalling catalyst\e[0m"
 	source "${CWORKDIR}/scripts/functions/init_stage3_seq" "$@" \
-	&& sinit_mon_f "CATALYST" || { print_inf_f 2 && exit; }
+	&& sinit_mon_f "CATALYST" || die "Calling catalyst failed"
 }
 
 catalyst_extr_tar_f() {
@@ -133,7 +155,7 @@ dep_c_f() {
 			case "${YN}" in
 				[yY])
 					echo -e "\e[34mChecking for dependencies\e[0m"
-					lcreq_f 1 || exit 1
+					lcreq_f 1 || die
 					sinit_mon_f "RDEP"
 					break;;
 				[nN])
@@ -157,7 +179,7 @@ dep_c_f() {
 			case "${YN:-n}" in
 				[yY])
 					echo -e "\e[34mChecking for dependencies\e[0m"
-					lcreq_f 2 || exit 1
+					lcreq_f 2 die
 					break;;
 				[nN])
 					echo "If you have not run a dependency check before, please abort"
@@ -187,8 +209,7 @@ check_pds_f(){
 	if [[ -n "$@" && -z "$(cat /proc/mounts | grep "workdir-$2")" ]]; then
 		rm -rf "$1"
 	else
-		print_inf_f 3
-		exit 1
+		print_inf_f
 	fi
 }
 
@@ -246,7 +267,7 @@ start_new_f() {
 }
 
 extract_tarball_f() {
-	[[ -z "$@" && -d "$2" ]] && print_inf 4 && return 1
+	[[ -z "$@" && -d "$2" ]] && die "Wrong Parameters"
 	mkdir -p "$2"
 
 	echo -e "\e[34mExtracting tarball\e[0m"
@@ -261,7 +282,7 @@ extract_tarball_f() {
 }
 
 check_dir_f() {
-	[[ -z "$@" && -d "$2" ]] && print_inf 4 && return 1
+	[[ -z "$@" && -d "$2" ]] && die "Wrong Parameters"
 	if [[ -n $(echo "$@" | grep '\--force-new') ]]; then
 		echo "This may take some time"
 		echo "Purging..."
@@ -317,14 +338,14 @@ export_dist_f() {
 }
 
 gentoo_key_f() {
-	[[ -z "${GENTOOKEY}" ]] && print_inf_f 4 && return 1
+	[[ -z "${GENTOOKEY}" ]] && die "Wrong Parameters" && return 1
 	gpg --keyserver hkps.pool.sks-keyservers.net --recv-keys >/dev/null 2>&1 ${GENTOOKEY} \
 	&& echo -e "[\e[32m*\e[0m]\e[32m Fetching Key\e[0m" \
 	|| { echo -e "[\e[31m*\e[0m]\e[31m Fetching Key\e[0m"; return 1; }
 }
 
 get_latest_f() {
-	[[ -z "${GENTOOLATEST}" || -z "${GENTOOLATESTASC}" ]] && print_inf_f 4 && return 1
+	[[ -z "${GENTOOLATEST}" || -z "${GENTOOLATESTASC}" ]] && die "Wrong Parameters" && return 1
 	mkdir -p "${CDISTDIR}/dists" \
 	&& echo -e "[\e[32m*\e[0m] Fetching \e[34m${STAGE3TB}\e[0m"
 	if [[ -n $(echo "$@" | grep '\--fetch-new') || -n $(echo "$@" | grep '\-fn') ]]; then
@@ -333,11 +354,11 @@ get_latest_f() {
 		rm -f "${CDISTDIR}/dists/stage3-${ARCH}-latest.tar.bz2.DIGESTS" >/dev/null 2>&1
 		wget -c -O "${CDISTDIR}/dists/stage3-${ARCH}-latest.tar.bz2" "${GENTOOLATEST}" >/dev/null 2>&1 \
 		&& echo "${STAGE3TB}" > "${CDISTDIR}/dists/latest.info" \
-		&& print_inf_f 1 || { print_inf_f 2; return 1; }
+		&& pass || die "FAILED"
 	else
 		wget -c -O "${CDISTDIR}/dists/stage3-${ARCH}-latest.tar.bz2" "${GENTOOLATEST}" \
 		&& echo "${STAGE3TB}" > "${CDISTDIR}/dists/latest.info" \
-		&& print_inf_f 1 || { print_inf_f 2; return 1; }
+		&& pass || die "FAILED"
 	fi
 	wget -c -O "${CDISTDIR}/dists/stage3-${ARCH}-latest.tar.bz2.DIGESTS.asc" "${GENTOOLATESTASC}" >/dev/null 2>&1 \
 	&& echo -e "[\e[32m*\e[0m] Fetching \e[34m${GENTOOLATEST}\e[0m" \
@@ -361,7 +382,7 @@ verify_download_f() {
 
 fetch_new_f() {
 	# CHECK FOR THE POSITIONAL PARAMETERS AND BAILOUT IF THEY ARE MISSING
-	[[ -z "$@" ]] && print_inf_f 4 && exit 1
+	[[ -z "$@" ]] && die "Wrong parameters"
 	if [[ -n $(echo "$@" | grep '\--force-new') ]]; then
 		echo -e "\e[33mSearching for tarball...\e[0m"
 		export_dist_f
@@ -405,35 +426,6 @@ fetch_new_f() {
 	fi
 }
 
-print_inf_f() {
-case $1 in
-	1)
-		echo -e "[\e[32m*\e[0m] \e[34mDone\e[0m";;
-	2)
-		echo -e "[\e[31m*\e[0m] \e[31mFAILED\e[0m";;
-	3)
-		clear
-		echo -e "[\e[31mFATAL\e[0m]"
-		echo -e "\e[31mIf this message is printed while using the Maim Menu\e[0m"
-		echo -e "\e[31mThat means essential files are altered or something bad is happening.\e[0m"
-		echo
-		echo -e "\e[31mPlease run a health-check from the ~Main Menu~ and a Version check first.\e[0m"
-		echo -e "\e[31mIf you see this again after the health/version check, please submit a bug report\e[0m"
-		echo -e "\e[31mand stop using the program, or data loss may occur.\e[0m"
-		echo
-		echo -e "\e[31mExiting...\e[0m"
-		sleep 5
-		exit 1;;
-	4)
-		echo -e "[\e[31m*\e[0m] [\e[31mERROR\e[0m: Wrong parameters"
-		exit 1;;
-	5)
-		echo -e "[\e[31m*\e[0m] Failed Fetching version";;
-	6)
-		echo -e "[\e[31m*\e[0m] FATAL";;
-esac
-}
-
 umnt_l_f() {
 	[[ -n "$(grep "dist.d/workdir-"$2 "/proc/mounts" | awk -F ' ' '{ print $2 }')" ]] \
 	&& while true; do
@@ -448,24 +440,24 @@ umnt_l_f() {
 }
 
 mount_dev_sys_f() {
-	[[ -z "$@" ]] && print_inf_f 3 && exit 1
+	[[ -z "$@" ]] && print_inf_f
 	mount --rbind /dev "$1/$2" \
 	&& mount --make-rslave "$1/$2" \
 	&& echo -e "[\e[32m*\e[0m] Mounting $2" \
-	|| { echo -e "[\e[31*\e[0m] Mounting $2"; return 1; }
+	|| { echo -e "[\e[31*\e[0m] Mounting $2"; die "Failed"; }
 }
 
 mount_proc_f() {
-	[[ -z "$@" ]] && print_inf_f 3 && exit 1
+	[[ -z "$@" ]] && print_inf_f 
 	mount -t proc /proc "$1/proc" \
 	&& echo -e "[\e[32m*\e[0m] Mounting proc" \
-	|| { echo -e "[\e[31m*\e[0m] Mounting proc"; return 1; }
+	|| { echo -e "[\e[31m*\e[0m] Mounting proc"; die "Failed"; }
 }
 
 pr_chroot_f() {
-	[[ -z "$@" ]] && print_inf_f 3 && exit 1
+	[[ -z "$@" ]] && print_inf_f
 
-	cp -L /etc/resolv.conf "$1/etc/" || exit 1
+	cp -L /etc/resolv.conf "$1/etc/" || die "Failed"
 
 	if [[ -n $(echo "$@" | grep 'catalyst') ]]; then
 		# CHECK IF PSEUDOS ARE MOUNTED
@@ -489,7 +481,7 @@ pr_chroot_f() {
 	fi \
 	&& mount_dev_sys_f "$1" "dev" \
 	&& mount_dev_sys_f "$1" "sys" \
-	|| { echo -e "[\e[31m*\e[0m] Something went wrong" && exit 1; }
+	|| { echo -e "[\e[31m*\e[0m] Something went wrong" && die "Failed"; }
 
 	mkdir -p "$1/sinit.d"
 
@@ -498,7 +490,7 @@ pr_chroot_f() {
 	&& rsync -aAXr "${CCONFDIR}/system/portage/" "$1/sinit.d/" >/dev/null 2>&1 \
 	&& rsync -aAXr --exclude="portage" "${CCONFDIR}/system/" "$1/sinit.d/" >/dev/null 2>&1 \
 	&& echo -e "[\e[32m*\e[0m] Copying \e[34mbuilder's\e[0m files to new system" \
-	|| { echo -e "[\e[31m*\e[0m] Copying \e[34mbuilder's\e[0m files to new system"; return 1; }
+	|| { echo -e "[\e[31m*\e[0m] Copying \e[34mbuilder's\e[0m files to new system"; die "Failed"; }
 
 	# CREATE REPOS.CONF DIRECOTRY & AND COPY REPOS.CONF TO IT
 	mkdir -p "$1/etc/portage/repos.conf"
@@ -519,7 +511,7 @@ pr_chroot_f() {
 			f2="${BWORKDIR}/(echo $INJFL | awk -F ' ' '{ print $2 }')"
 			echo "Copying $f1 to $f2"
 			rsync -aAXPhrv "$f1" "$f2" >/dev/null 2>&1 \
-			&& print_inf 1 || { print_inf 2 mapfile -t INJFLERR < <($INJFL | awk -F ' ' '{ print $1 }'); }
+			&& pass || { mapfile -t INJFLERR < <($INJFL | awk -F ' ' '{ print $1 }'); }
 		done < <(cat "${CCONFDIR}/system/inject_files" | sed '/^#/ d' | sed '/^\s*$/d')
 		unset INJFL
 
@@ -577,7 +569,7 @@ pr_chroot_f() {
 
 	echo -e "\e[34mChrooting at new system\e[0m"
 	sleep 2
-	chroot "$1" "sinit.d/chroot_init" "$@" || { echo -e "[\e[31m*\e[0m] Chrooting at new system"; return 1; } \
+	chroot "$1" "sinit.d/chroot_init" "$@" || { echo -e "[\e[31m*\e[0m] Chrooting configuration failed"; die; } \
 	&& sinit_mon_f "PARTB"
 }
 
@@ -586,7 +578,7 @@ lcreq_f() {
 	CRDPENDS=''
 	amiroot_sub_f() {
 	if [[ "$1" == "0" ]]; then
-			return 0
+		return 0
 	else
 		return 1
 	fi
