Included functions for custom scripts

diff --git a/scripts/chroot_scripts/chroot_init b/scripts/chroot_scripts/chroot_init
--- a/scripts/chroot_scripts/chroot_init
+++ b/scripts/chroot_scripts/chroot_init
@@ -12,7 +12,7 @@ if echo "${_flag_tty}" | grep -q 'sshd'; then
 	LC_ALL="en_US.UTF-8"
 	LC_CTYPE="en_US.UTF-8"
 fi
-
+echo "$@"
 source /etc/profile && export PS1="( 'Part C: Preparing to bootstrap' ) $PS1"
 export CHDIR="/sinit.d"
 export PATH=${PATH}:${CHDIR}
@@ -23,40 +23,69 @@ source "${CHDIR}/chinit.conf" \
 
 inspector "$@"
 
+if grep -q '\-gupdate' "${CHDIR}/cscripts/doscripts"; then
+	_e_report_back "Sourcing scripts before Part: Portage Update"
+	_do_rs '\-gupdate'
+fi
+
 # PART C BEGINS
-if [[ "$(awk -F '=' '/UPDATE/{ print $2 }' <"${CHDIR}/chsinprog")" == 0 || -n $(echo "${_flag_force_new}") ]]; then
-	_part_c "$@" || die "Part C FAILED"
+if echo "${_lawful_args[@]}" | grep -q 'gupdate'; then
+	_e_report_back "Update and prepare system: Lawful entry detected, proceeding..."
 else
-	if echo "${_lawful_args[@]}" | grep -q 'gupdate'; then
-		_e_report_back "Update and prepare system: Lawful entry detected, proceeding..."
-	else
+	if [[ "$(awk -F '=' '/UPDATE/{ print $2 }' <"${CHDIR}/chsinprog")" == 0 || -n "${_flag_force_new}" ]] || echo "${_enforce_args[@]}" | grep -q 'gupdate'; then
 		if echo "${_enforce_args[@]}" | grep -q 'gupdate'; then
-			_e_report_back "Update and prepare system: Enforce entry detected, forcing..."
+			_e_report_back "Update and prepare system: Force entry detected, forcing..."
 			_part_c "$@" "cforce" || die "Part C FAILED"
 		else
-			if repeat_part "Portage Update"; then
-				_part_c "$@" || die "Part C FAILED"
-			fi
+			_part_c "$@" || die "Part C FAILED"
+		fi
+	else
+		if repeat_part "Portage Update"; then
+			_part_c "$@" || die "Part C FAILED"
+		else
+			_e_report_back "Proceeding to sub portage part"
 		fi
 	fi
 fi
 
+if grep -q '\+gupdate' "${CHDIR}/cscripts/doscripts"; then
+	_e_report_back "Sourcing scripts after Part: Portage Update"
+	_do_rs '\+gupdate'
+fi
+
+if grep -q '\-gportage' "${CHDIR}/cscripts/doscripts"; then
+	_e_report_back "Sourcing scripts before Part: Portage"
+	_do_rs '\-gportage'
+fi
+
 # PART PORTAGE, PROFILE AND FEATURES UPDATE
-if [[ "$(awk -F '=' '/UPDATE/{ print $2 }' < "${CHDIR}/chsinprog")" == 0 || -n $(echo "${_flag_force_new}") ]]; then
-	part_portage "$@" && _monitor_chroot_flow "PORTAGE"
+if echo "${_lawful_args[@]}" | grep -q 'gportage'; then
+	_e_report_back "Portage Configuration: Lawful entry detected, proceeding..."
 else
-	if echo "${_lawful_args[@]}" | grep -q 'gportage'; then
-		_e_report_back "Portage Configuration: Lawful entry detected, proceeding..."
-	else
+	if [[ "$(awk -F '=' '/UPDATE/{ print $2 }' < "${CHDIR}/chsinprog")" == 0 || -n "${_flag_force_new}" ]] || echo "${_enforce_args[@]}" | grep -q 'gportage'; then
 		if echo "${_enforce_args[@]}" | grep -q 'gportage'; then
-			_e_report_back "Portage configuration: Enforce entry detected, forcing..."
+			_e_report_back "Portage configuration: Force entry detected, forcing..."
 			part_portage "$@" "cforce" && _monitor_chroot_flow "PORTAGE"
 		else
-			if repeat_part "Portage Configuration"; then
-				part_portage "$@" && _monitor_chroot_flow "PORTAGE"
-			fi
+			part_portage "$@" && _monitor_chroot_flow "PORTAGE"
+		fi		
+	else
+		if repeat_part "Portage Configuration"; then
+			part_portage "$@" && _monitor_chroot_flow "PORTAGE"
+		else
+			_e_report_back "Proceeding"
 		fi
 	fi
+fi
+
+if grep -q '\+gportage' "${CHDIR}/cscripts/doscripts"; then
+	_e_report_back "Sourcing scripts after Part:Portage"
+	_do_rs '\+gportage'
+fi
+
+if grep -q '\-grebuild' "${CHDIR}/cscripts/doscripts"; then
+	_e_report_back "Sourcing scripts before Part: System Rebuild"
+	_do_rs '\-grebuild'
 fi
 
 # Part D Begins
@@ -68,121 +97,186 @@ _sreb() {
 	_monitor_chroot_flow "REBUILD"
 }
 
-if [[ "$(awk -F '=' '/REBUILD/{ print $2 }' <"${CHDIR}/chsinprog")" == 0 || -n $(echo "${_flag_force_new}") ]]; then
-	if echo "${_lawful_args[@]}" | grep -q 'grebuild'; then
-		_e_report_back "System Rebuild: Lawful entry detected, proceeding..."
-	else
+if echo "${_lawful_args[@]}" | grep -q 'grebuild'; then
+	_e_report_back "Rebuild: Lawful entry detected, proceeding..."
+else
+	if [[ "$(awk -F '=' '/REBUILD/{ print $2 }' <"${CHDIR}/chsinprog")" == 0 || -n "${_flag_force_new}" ]] || echo "${_enforce_args[@]}" | grep -q 'grebuild'; then
 		if echo "${_enforce_args[@]}" | grep -q 'grebuild'; then
-			_e_report_back "System Rebuild: Enforce entry detected, forcing..."
-			_sreb "cforce"
-		else
-			_sreb
+			_e_report_back "System Rebuild: Force entry detected, forcing..."
 		fi
+			_sreb
 	fi
+fi
+
+if grep -q '\+grebuild' "${CHDIR}/cscripts/doscripts"; then
+	_e_report_back "Sourcing scripts after Part: System Rebuild"
+	_do_rs '\+grebuild'
+fi
+
+if grep -q '\-gconfigure' "${CHDIR}/cscripts/doscripts"; then
+	_e_report_back "Sourcing scripts before Part: Emerge Packages"
+	_do_rs '\-gconfigure'
 fi
 
 # PART E BEGINS
-if [[ "$(awk -F '=' '/CONFIGURE/{ print $2 }' <"${CHDIR}/chsinprog")" == 0 || -n $(echo "${_flag_force_new}") ]]; then
-	configure_system_f "$@"
+if echo "${_lawful_args[@]}" | grep -q 'gconfigure'; then
+	_e_report_back "System Configuration: Lawful entry detected, proceeding..."
 else
-	if echo "${_lawful_args[@]}" | grep -q 'gconfigure'; then
-		_e_report_back "System Configuration: Lawful entry detected, proceeding..."
-	else
+	if [[ "$(awk -F '=' '/CONFIGURE/{ print $2 }' <"${CHDIR}/chsinprog")" == 0 || -n "${_flag_force_new}" ]] || echo "${_enforce_args[@]}" | grep -q 'gconfigure'; then
 		if echo "${_enforce_args[@]}" | grep -q 'gconfigure'; then
-			_e_report_back "System Configuration: Enforce entry detected, forcing..."
+			_e_report_back "System Configuration: Force entry detected, forcing..."
 			configure_system_f "$@" "cforce"
 		else
-			if repeat_part "System Configuration"; then
-				configure_system_f "$@"
-			fi
+			configure_system_f "$@"
 		fi
+	else
+		if repeat_part "System Configuration"; then
+			configure_system_f "$@"
+		else
+			_e_report_back "Proceeding to emerging packages"
+		fi	
 	fi
+fi
+
+if grep -q '\+gconfigure' "${CHDIR}/cscripts/doscripts"; then
+	_e_report_back "Sourcing scripts after Part: Emerge Packages"
+	_do_rs '\+gconfigure'
+fi
+
+if grep -q '\-ginst' "${CHDIR}/cscripts/doscripts"; then
+	_e_report_back "Sourcing scripts before Part: Configuration"
+	_do_rs '\-ginst'
 fi
 
 # PART F BEGINS
-if [[ "$(awk -F '=' '/INSTALL/{ print $2 }' <"${CHDIR}/chsinprog")" == 0 || -n $(echo "${_flag_force_new}") ]]; then
-	emerge_requested "$@"
+if echo "${_lawful_args[@]}" | grep -q 'ginst'; then
+	_e_report_back "Emerge packages: Lawful entry detected, proceeding..."
 else
-	if echo "${_lawful_args[@]}" | grep -q 'ginst'; then
-		_e_report_back "Emerge packages: Lawful entry detected, proceeding..."
-	else
+	if [[ "$(awk -F '=' '/INSTALL/{ print $2 }' <"${CHDIR}/chsinprog")" == 0 || -n "${_flag_force_new}" ]] || echo "${_enforce_args[@]}" | grep -q 'ginst'; then
 		if echo "${_enforce_args[@]}" | grep -q 'ginst'; then
-			_e_report_back "Emerge packages: Enforce entry detected, forcing..."
+			_e_report_back "Emerge packages: Force entry detected, forcing..."
 			emerge_requested "$@" "cforce"
 		else
-			if repeat_part "Installing Packages"; then
-				emerge_requested "$@"
-			fi
+			emerge_requested "$@"
+		fi			
+	else
+		if repeat_part "Installing Packages"; then
+			emerge_requested "$@"
+		else
+			_e_report_back "Proceeding to runlevel update"
 		fi
 	fi
 fi
 unset YN
+
+if grep -q '\+ginst' "${CHDIR}/cscripts/doscripts"; then
+	__e_report_back "Sourcing scripts after Part: Configuration"
+	_do_rs '\+ginst'
+fi
+
+if grep -q '\-grun' "${CHDIR}/cscripts/doscripts"; then
+	_e_report_back "Sourcing scripts before Part: Runlevels"
+	_do_rs '\-grun'
+fi
 
 # PART G BEGINS
-if [[ "$(awk -F '=' '/RUNLEVEL/{ print $2 }' <"${CHDIR}/chsinprog")" == 0 || -n $(echo "${_flag_force_new}") ]]; then
-	_runlevel_configuration
+if echo "${_lawful_args[@]}" | grep -q 'grun'; then
+	_e_report_back "Runlevel: Lawful entry detected, proceeding..."
 else
-	if echo "${_lawful_args[@]}" | grep -q 'grun'; then
-		_e_report_back "Runlevel: Lawful entry detected, proceeding..."
-	else
+	if [[ "$(awk -F '=' '/RUNLEVEL/{ print $2 }' <"${CHDIR}/chsinprog")" == 0 || -n "${_flag_force_new}" ]] || echo "${_enforce_args[@]}" | grep -q 'grun'; then
 		if echo "${_enforce_args[@]}" | grep -q 'grun'; then
-			_e_report_back "Runlevel: Enforce entry detected, forcing..."
-			_runlevel_configuration "cforce"
+			_e_report_back "Runlevel: Force entry detected, forcing..."
+		fi
+			_runlevel_configuration
+	else
+		if repeat_part "Runlevel Configuration"; then
+			_runlevel_configuration
 		else
-			if repeat_part "Runlevel Configuration"; then
-				_runlevel_configuration
-			fi
+			_e_report_back "Proceeding"
 		fi
 	fi
 fi
 unset YN
 
+if grep -q '\+grun' "${CHDIR}/cscripts/doscripts"; then
+	_e_report_back "Sourcing scripts after Part: Runlevels"
+	_do_rs '\+grun'
+fi
+
+if grep -q '\-gkernel' "${CHDIR}/cscripts/doscripts"; then
+	_e_report_back "Sourcing scripts before Part: kernel"
+	_do_rs '\-gkernel'
+fi
+
 # PART H BEGINS
-if [[ -n "$(echo "${_flag_kernel}")" ]] || [[ -n "$(echo "${_flag_minimal}")" ]]; then
+if [[ -n "${_flag_kernel}" ]] || [[ -n "${_flag_minimal}" ]]; then
 	:
 else
-	if [[ "$(awk -F '=' '/KERNEL/{ print $2 }' <"${CHDIR}/chsinprog")" == 0 || -n $(echo "${_flag_force_new}") ]]; then
-		_kernel_build
+	if echo "${_lawful_args[@]}" | grep -q 'gkernel'; then
+		_e_report_back "Kernel: Lawful entry detected, proceeding..."
 	else
-		if echo "${_lawful_args[@]}" | grep -q 'gkernel'; then
-			_e_report_back "Kernel: Lawful entry detected, proceeding..."
-		else
+		if [[ "$(awk -F '=' '/KERNEL/{ print $2 }' <"${CHDIR}/chsinprog")" == 0 || -n $(echo "${_flag_force_new}") ]] || echo "${_enforce_args[@]}" | grep -q 'gkernel'; then
 			if echo "${_enforce_args[@]}" | grep -q 'gkernel'; then
-				_e_report_back "Kernel: Enforce entry detected, forcing..."
+				_e_report_back "Kernel: Force entry detected, forcing..."
 				_kernel_build "cforce"
 			else
-				if repeat_part "Kernel Configuration"; then
-					_kernel_build
-				fi
+				_kernel_build
+			fi
+		else
+			if repeat_part "Kernel Configuration"; then
+				_kernel_build
+			else
+				_e_report_back "Proceeding"
 			fi
 		fi
 	fi
 	unset YN
+fi
+
+if grep -q '\+gkernel' "${CHDIR}/cscripts/doscripts"; then
+	_e_report_back "Sourcing scripts after Part: Kernel"
+	_do_rs '\+gkernel'
+fi
+
+if grep -q '\-ginitrd' "${CHDIR}/cscripts/doscripts"; then
+	_e_report_back "Sourcing scripts before Part: Initrd"
+	_do_rs '\-ginitrd'
 fi
 
 # PART I BEGINS
-if [[ -n "$(echo "${_flag_kernel}")" ]] || [[ -n "$(echo "${_flag_minimal}")" ]] || [[ -n "$(echo "${_flag_initrd}")" ]]; then
+if [[ -n "${_flag_kernel}" ]] || [[ -n "${_flag_minimal}" ]] || [[ -n "${_flag_initrd}" ]]; then
 	:
 else
-	if [[ "$(awk -F '=' '/INITRAMFS/{ print $2 }' <"${CHDIR}/chsinprog")" == 0 || -n $(echo "${_flag_force_new}") ]]; then
-		_initramfs_builder
+	if echo "${_lawful_args[@]}" | grep -q 'ginitrd'; then
+		_e_report_back "Initramfs: Lawful entry detected, proceeding..."
 	else
-		if echo "${_lawful_args[@]}" | grep -q 'ginitrd'; then
-			_e_report_back "Initramfs: Lawful entry detected, proceeding..."
-		else
-			if echo "${_enforce_args[@]}" | grep -q 'gkernel'; then
-				_e_report_back "Initramfs: Enforce entry detected, forcing..."
+		if [[ "$(awk -F '=' '/INITRAMFS/{ print $2 }' <"${CHDIR}/chsinprog")" == 0 || -n "${_flag_force_new}" ]] || echo "${_enforce_args[@]}" | grep -q 'ginitrd'; then
+			if echo "${_enforce_args[@]}" | grep -q 'ginitrd'; then
+				_e_report_back "Initramfs: Force entry detected, forcing..."
 				_initramfs_builder "cforce"
 			else
-				if repeat_part "Initramfs Configuration"; then
-					_initramfs_builder
-				fi
+				_initramfs_builder
+			fi
+		else
+			if repeat_part "Initramfs Configuration"; then
+				_initramfs_builder
+			else
+				_e_report_back "Proceeding"
 			fi
 		fi
 	fi
 	unset YN
 fi
 
+if grep -q '\+ginitrd' "${CHDIR}/cscripts/doscripts"; then
+	_e_report_back "Sourcing scripts after Part: Initrd"
+	_do_rs '\+ginitrd'
+fi
+
+if grep -q '\-gdes' "${CHDIR}/cscripts/doscripts"; then
+	_e_report_back "Sourcing scripts before Part: Deselect packages"
+	_do_rs '\-gdes'
+fi
 
 eclean-dist -d
 eclean-pkg -d
@@ -203,6 +297,10 @@ fi
 
 _emerge_depclear
 
+if grep -q '\+gdes' "${CHDIR}/cscripts/doscripts"; then
+	_e_report_back "Sourcing scripts after Part: Deselect packages"
+	_do_rs '\+gdes'
+fi
 
 # Creating user-data dir-tree
 mkdir -p /user-data/persistent/{etc,var,logs,config.d,local,rmount}
diff --git a/scripts/functions/sinit_functions b/scripts/functions/sinit_functions
--- a/scripts/functions/sinit_functions
+++ b/scripts/functions/sinit_functions
@@ -13,13 +13,6 @@ _subshell() {
 }
 
 parameters_check() {
-	if [[ -z "$(echo "$@" | grep '\--fetch-new')" && -z "$(echo "$@" | grep '\-fn')" ]]; then
-		if [[ -z "$(echo "$@" | grep '\--base')" && -z "$(echo "$@" | grep '\-b')" ]]; then
-			_e_report_back "You must choose a base if your run gse without main menu. Aborting..."
-			_e_report_back "See man 1 gse for base options."
-			die "Aborting actions..."
-		fi
-	fi
 
 	if [[ -n $(echo "$@" | grep '\--force-new') ]] && [[ -n $(echo "$@" | grep '\--lawful-good') || -n $(echo "$@" | grep '\-lg') ]]; then
 		die "Warning: --force-new suppresses --lawful-good"
@@ -144,7 +137,7 @@ print_inf_f() {
 	exit 1
 }
 
-repeat_parta() {
+repeat_part() {
 	while true; do
 		echo -e "\e[33mPart $1: Has been completed\e[0m"
 		echo "Run again? Y/N: "
@@ -452,7 +445,7 @@ _get_latest() {
 	inspector "$@"
 	[[ -z "${GENTOOLATEST}" || -z "${GENTOOLATESTASC}" ]] && die "Wrong Parameters" && return 1
 	mkdir -p "${CDISTDIR}/dists"
-	if [[ -n "$(echo "$@" | grep 'fetch_new')" ]]; then
+	if [[ -n "${_flag_fetch}" ]] || echo "$@" | grep -q 'force'; then
 		echo -e "[\e[34m*\e[0m] Marking stage3-${ARCH}-latest.tar.bz2 for purging"
 		burn "${CDISTDIR}/dists/stage3-${ARCH}-latest.tar.bz2"
 		echo -e "[\e[34m*\e[0m] Marking stage3-${ARCH}-latest.tar.bz2.DIGESTS.asc for purging"
@@ -496,30 +489,30 @@ _call_fetch_new() {
 }
 
 _seed_net() {
-	if [[ $(echo "${_flag_network}") == 0 ]]; then
-		if [[ "$(awk -F '=' '/SEED/{ print $2 }' < "${CLOCALLG}/sinprog")" == 0 ]] || echo "$@" | grep -q 'force'; then
-			_fetch_new "$@" || die "FAILED"
-		else
-			if [[ -n "$(echo "${_lawful_args[@]}" | grep 'gseed')" ]]; then
-				_e_report_back "Fetch: Lawful entry detected, proceeding..."
-			else
+	if [[ -n "$(echo "${_lawful_args[@]}" | grep 'gseed')" ]]; then
+		_e_report_back "Fetch: Lawful entry detected, proceeding..."
+	else	
+		if [[ $(echo "${_flag_network}") == 0 ]]; then
+			if [[ "$(awk -F '=' '/SEED/{ print $2 }' < "${CLOCALLG}/sinprog")" == 0 ]] || echo "$@" | grep -q 'force' || echo "${_enforce_args[@]}" | grep 'gseed'; then
 				if echo "${_enforce_args[@]}" | grep 'gseed'; then
 					_e_report_back "Fetch: Enforce entry detected, forcing..."
 					_fetch_new "$@" "force" || die "FAILED"
 				else
-					if _repeat_subpart "Tarball" "fetched"; then
-						_fetch_new "$@" || die "FAILED"
-					else	
-						_e_report_back "Proceeding on next part..."
-					fi
+					_fetch_new "$@" || die "FAILED"
+				fi
+			else
+				if _repeat_subpart "Tarball" "fetched"; then
+					_fetch_new "$@" || die "FAILED"
+				else	
+					_e_report_back "Proceeding on next part..."
 				fi
 			fi
+		elif [[ ! -e "${CDISTDIR}/dists/stage3-${ARCH}-latest.tar.bz2" ]]; then
+			die "No local tarball is present. Please enable network connection and try again"
+		elif [[ -e "${CDISTDIR}/dists/stage3-${ARCH}-latest.tar.bz2" ]]; then
+			_e_report_back "Stage3 tarball located"
+			_e_report_back "Calling catalyst"
 		fi
-	elif [[ ! -e "${CDISTDIR}/dists/stage3-${ARCH}-latest.tar.bz2" ]]; then
-		die "No local tarball is present. Please enable network connection and try again"
-	elif [[ -e "${CDISTDIR}/dists/stage3-${ARCH}-latest.tar.bz2" ]]; then
-		_e_report_back "Stage3 tarball located"
-		_e_report_back "Calling catalyst"
 	fi
 }
 
@@ -544,8 +537,16 @@ _call_force_new() {
 _fetch_new() {
 	# CHECK FOR THE POSITIONAL PARAMETERS AND BAILOUT IF THEY ARE MISSING
 	[[ -z "$@" ]] && die "Wrong parameters"
-	if echo "$@" | grep -q 'force'; then
-		echo -e "\e[33mSearching for tarball...\e[0m"
+	echo -e "\e[33mSearching for tarball...\e[0m"
+	if [[ -n "${_flag_fetch}" ]] || echo "$@" | grep -q 'force'; then
+		_export_latest
+		# FETCH THE KEYS FOR THE CRYPTOGRAPHIC AUTHENTICATION
+		_gentoo_key
+		# GET LATEST STAGE3 TARBALL, .DIGEST && .DIGEST.asc
+		_get_latest "$@"
+		# VERIFY THE AUTHENTICATION OF THE DOWNLOADED FILES
+		_verify_download
+	else
 		_export_latest
 		# GET LATEST STAGE3 TARBALL, .DIGEST && .DIGEST.asc
 		local_stage3="$(cat "${CDISTDIR}/dists/latest.info")"
@@ -555,34 +556,9 @@ _fetch_new() {
 			# FETCH THE KEYS FOR THE CRYPTOGRAPHIC AUTHENTICATION
 			_gentoo_key
 			# GET LATEST STAGE3 TARBALL, .DIGEST && .DIGEST.asc
-			_get_latest "$@"
+			_get_latest "$@" "fetch_new"
 			# VERIFY THE AUTHENTICATION OF THE DOWNLOADED FILES
 			_verify_download
-		fi
-	else
-		echo -e "\e[33mSearching for tarball...\e[0m"
-		if [[ -n "${_flag_fetch}" || "$1" == 'fetch_new' ]]; then
-			_export_latest
-			# FETCH THE KEYS FOR THE CRYPTOGRAPHIC AUTHENTICATION
-			_gentoo_key
-			# GET LATEST STAGE3 TARBALL, .DIGEST && .DIGEST.asc
-			_get_latest "$@"
-			# VERIFY THE AUTHENTICATION OF THE DOWNLOADED FILES
-			_verify_download
-		else
-			_export_latest
-			# GET LATEST STAGE3 TARBALL, .DIGEST && .DIGEST.asc
-			local_stage3="$(cat "${CDISTDIR}/dists/latest.info")"
-			if [[ "${local_stage3}" == "${STAGE3TB}" ]]; then
-				echo -e "[\e[32m*\e[0m] Latest stage3 is already present locally"
-			else
-				# FETCH THE KEYS FOR THE CRYPTOGRAPHIC AUTHENTICATION
-				_gentoo_key
-				# GET LATEST STAGE3 TARBALL, .DIGEST && .DIGEST.asc
-				_get_latest "$@"
-				# VERIFY THE AUTHENTICATION OF THE DOWNLOADED FILES
-				_verify_download
-			fi
 		fi
 	fi
 }
@@ -737,6 +713,14 @@ _prepare_chroot() {
 		echo -e "[\e[32m*\e[0m] List empty"
 	fi
 
+# COPY THE SCRIPTS AND DOSCRIPTS AT CHROOTDIR
+	if [[ -n "${_flag_sdir}" ]]; then
+		mkdir -p "$1/sinit.d/cscripts"
+		rsync -aAXhrvq "${_flag_sdir_path}/" "$1/sinit.d/cscripts/"
+		chmod +x "$1/sinit.d/cscripts/"*
+		cp -r "${CLOCALLG}/doscripts" "$1/sinit.d/cscripts/doscripts"
+	fi
+
 	echo -e "\e[34mChrooting at new system\e[0m"
 	sleep 0.5
 	# PASS ALL PP AND INITIATE CHROOT
@@ -842,6 +826,8 @@ _case_args() {
 			_on_eargs+=("$1");;
 		ginitrd		)
 			_on_eargs+=("$1");;
+		gdes		)
+			_on_eargs+=("$1");;
 		gpartb		)
 			_on_eargs+=("$1");;
 		*			)
@@ -859,7 +845,7 @@ _export_args() {
 			die "No arguments were set for $2. Aborting..."
 		else
 			declare -a _ARGARRAY=("gfund" "gseed" "gcat" "gextr" "gprec" "gparta" \
-				"gupdate" "gportage" "grebuild" "gconfigure" "ginst" "grun" "gkernel" "ginitrd" "gpartb")	
+				"gupdate" "gportage" "grebuild" "gconfigure" "ginst" "grun" "gkernel" "ginitrd" "gpartb" "gdes" "gclean")	
 
 			_on_eargs=()
 			if [[ $(echo "${_check_args}" | cut -d ',' -f 1) == $(echo "${_check_args}" | cut -d ',' -f 2) ]]; then
@@ -906,6 +892,9 @@ librarium() {
 	_flag_silent=''
 	_flag_network=''
 	_flag_mm=''
+	_flag_do=''
+	_flag_g=''
+	_flag_sdir=''
 	while true; do
 		[[ -z "$@" ]] && return 0
 		case "$1" in
@@ -932,11 +921,13 @@ librarium() {
 						case "${_base_method}" in
 							catalyst 	)
 								_flag_base="catalyst"
-								_e_report_back "Base: catalyst"
+								_e_report_back "Selected Base "
+								_o_report_back "catalyst"
 								export _flag_base;;
 							precomp 	)
 								_flag_base="precomp"
-								_e_report_back "Base: precomp"
+								_e_report_back "Selected Base "
+								_o_report_back "precomp"
 								export _flag_base;;
 							*			)
 								die "Wrong target base. Choose either catalyst or precomp"
@@ -1002,7 +993,6 @@ librarium() {
 				export _flag_minimal;;
 		
 			--enforce*					)
-				echo "$1"
 				_export_args "$1" "enforce"
 				_enforce_args=()
 				for i in "${_on_eargs[@]}"; do
@@ -1013,7 +1003,7 @@ librarium() {
 				_flag_enforce=0
 				export _flag_enforce
 				_e_report_back "The following enforcer arguments have been enabled"
-				_e_report_back "${_enforce_args[@]}"
+				_o_report_back "${_enforce_args[@]}"
 				;;
 		
 			--lawful-good*				)
@@ -1027,7 +1017,7 @@ librarium() {
 				_flag_lawful=0
 				export _flag_lawful
 				_e_report_back "The following lawful arguments have been enabled"
-				_e_report_back "${_lawful_args[@]}"
+				_o_report_back "${_lawful_args[@]}"
 				;;
 
 			--verbose|-v 				)
@@ -1041,8 +1031,84 @@ librarium() {
 				export _flag_quiet;;
 			-mm 						)
 				_flag_mm=0
-				export _flag_m;;
-		
+				export _flag_mm;;
+			--sdir*)
+				if [[ -z "$(echo "$1" | grep '=')" ]]; then
+					die "Missing argument for script's dir path"
+				else
+					_flag_sdir_path="${1#*=}"
+					[[ ${_flag_sdir_path:0:1} != "/" ]] && _flag_sdir_path="/${_flag_sdir_path}"
+					if [[ -d "${_flag_sdir_path}" ]]; then
+						_flag_sdir=0
+						export _flag_sdir
+						export _flag_sdir_path
+						_e_report_back "Script's dir flag enabled"
+					else
+						die "Error: script's dir target is not a directory"
+					fi
+				fi
+				
+				if [[ -z "$(echo "$2" | grep '\--do')" ]]; then
+					die "Missing --do flag"
+				fi
+
+				if [[ -z "$(echo "$2" | grep '=')" ]]; then
+					die "Missing --do arguments"
+				fi
+
+				if [[ -z "$(echo "$3" | grep '\-g')" ]]; then
+					die "Missing -g flag"
+				fi
+
+				if [[ -z "$(echo "$3" | grep '=')" ]]; then
+					die "Missing argument after -g"
+				fi
+				
+				_flag_doargs="${2#*=}"
+				_flag_gargs="${3#*=}"
+
+				echo "# Requested Scripts" > "${CLOCALLG}/doscripts"
+				echo "# SCRIPT'S PATH" >> "${CLOCALLG}/doscripts"
+				echo "SCP:${_flag_sdir_path}" >> "${CLOCALLG}/doscripts"
+				echo "# Hook:Script" >> "${CLOCALLG}/doscripts"
+				for i in {1..14}; do
+					if [[ -n "$(echo "${_flag_doargs}" | awk -v j="$i" -F ' ' '{print $j}')" ]]; then
+						if [[ -n "$(echo "${_flag_gargs}" | awk -v j="$i" -F ',' '{print $j}')" ]]; then
+							GVAR0="$(echo "${_flag_gargs}" | awk -v j="$i" -F ',' '{print $j}')"
+							if [[ "$(echo "${GVAR0:0:1}")" == '+' || "$(echo "${GVAR0:0:1}")" == '-' ]]; then
+								GVAR1="${GVAR0:1}"
+								if _case_args "${GVAR1}"; then
+									:
+								fi
+							else
+								die "Missing + or - from $(echo "${_flag_gargs}" | awk -v j="$i" -F ',' '{print $j}')"
+							fi
+						else
+							die "Missing hook point for ${DOVAR1}"
+						fi
+
+						DOVAR0="$(echo "${_flag_doargs}" | awk -v j="$i" -F ' ' '{print $j}')"
+						l=1
+						while true; do
+							if [[ -n "$(echo "${DOVAR0}" | awk -v k="$l" -F ',' '{print $k}')" ]]; then
+								DOVAR1="$(echo "${DOVAR0}" | awk -v k="$l" -F ',' '{print $k}')"
+								if [[ ! -e "${_flag_sdir_path}/${DOVAR1}" ]]; then
+									die "There is no such a ${DOVAR1} file"
+								fi
+								echo "${GVAR0}:${DOVAR1}" >> "${CLOCALLG}/doscripts"
+							else
+								break
+							fi
+							((++l))
+						done
+					else
+						break
+					fi
+				done
+				_e_report_back "With hooked scripts at: "
+				_o_report_back "$(cat "${CLOCALLG}/doscripts")"
+				shift 2
+				;;
 			--test						)
 				_e_report_back "Test flag is enabled"
 				_flag_test=0
@@ -1100,7 +1166,7 @@ witch_hunt() {
 
 	# CHECK FOR SUPERUSER PRIVILAGES
 	if _am_i_root "$UID"; then
-		_e_report_back "Superuser detected"
+		_o_report_back "Superuser detected"
 	else
 		die "User is not superuser. Aborting"
 	fi
@@ -1108,15 +1174,15 @@ witch_hunt() {
 	# PRIORITY CHECK FOR THE SCRIPT'S PID
 	if [[ "$(ps -fl $$ | tail -n +2 | awk -F ' ' '{ print $8}')" -le 0 ]]; then
 		_e_report_back "The priority of $0 is not high, and currently greater or equal to 0"
-		_e_report_back "Changing priority to -5"
+		_o_report_back "Changing priority to -5"
 		renice -n -5 -p "$$" >/dev/null
 	fi
 
 	# ISSUE WARNING IF CONNECTION SEEMS TO BE FROM SSHD
 	if [[ -n "${SSH_CLIENT}" || -n "${SSH_TTY}" ]]; then
 		if [[ "$(echo "${TERM}")" == "screen" ]]; then
-			_e_report_back "Session detected: ssh"
-			_e_report_back "Tmux/Screen detected"
+			_o_report_back "Session detected: ssh"
+			_o_report_back "Tmux/Screen detected"
 			_flag_tty="sshd"
 			export _flag_tty
 		else
@@ -1234,6 +1300,12 @@ warp() {
 	# FILTER AND EXPORT ALL FLAGS AND ARGUMENTS. DIE UNLESS CONDITIONS ARE EXACT
 	librarium "$@"
 
+	if [[ -z "${_flag_base}" ]]; then
+		_e_report_back "You must choose a base if your run gse without main menu. Aborting..."
+		_e_report_back "See man 1 gse for base options."
+		die "Aborting actions..."
+	fi
+
 	# THIS FUNCTION WILL ISSUE ESSENTIAL SYSTEM CHECKS, BEFORE PROCEEDING.
 	inquisitor "$@"
 
@@ -1258,37 +1330,43 @@ warp() {
 	# STAGE A
 
 	# THIS LIST WILL BE EXPORTED TO THE SOURCED SINIT BUILDER SCRIPT
+	_flags_stagea=()
+
+	_flags_listA=("_flag_fetch" \
+		"_flag_force_new" \
+		"_flag_keep" \
+		"_flag_minimal" \
+		"_flag_enforce" \
+		"_enforce_args" \
+		"_flag_lawful" \
+		"_lawful_args" \
+		"_flag_verbose" \
+		"_flag_quiet" \
+		"_flag_test" \
+		"_flag_network" \
+		"_flag_base")
+
+	for i in "${_flags_listA[@]}"; do
+		if [[ "$(echo ${!i})" == 0 ]]; then
+			_flags_stagea+=("${i}")
+		fi
+	done
+	
 	if [[ -n "${_flag_base}" ]]; then
-		_flags_stagea=()
-
-		_flags_listA=("_flag_fetch" \
-			"_flag_force_new" \
-			"_flag_keep" \
-			"_flag_minimal" \
-			"_flag_enforce" \
-			"_enforce_args" \
-			"_flag_lawful" \
-			"_lawful_args" \
-			"_flag_verbose" \
-			"_flag_quiet" \
-			"_flag_test" \
-			"_flag_network" \
-			"_flag_base")
-
-		for i in "${_flags_listA[@]}"; do
-			if [[ "$(echo ${!i})" == 0 ]]; then
-				_flags_stagea+=("${i}")
-			fi
-		done
-
 		source "${CWORKDIR}/scripts/sinit" "${_flags_stagea[@]}"
-	else
-		_fetch_new "fetch_new"
+	elif [[ -z "${_flag_base}" && -n "${_flag_fetch}" ]]; then
+		_call_fetch_new "$@"
 	fi
+
 	# STAGE B
 
 	# STAGE C
 
 }
 
+_do_rs() {
+	while read -r s;do
+		source "${_flag_sdir_path}/$s"
+	done < <(grep "$1" "${CLOCALLG}/doscripts" | sed '/^#/ d' | sed '/^\s*$/d' | awk -F ':' '{ print $2 }')
+}
 
diff --git a/scripts/sinit b/scripts/sinit
--- a/scripts/sinit
+++ b/scripts/sinit
@@ -6,6 +6,12 @@ if echo "${_flag_tty}" | grep -q 'sshd'; then
 	LC_CTYPE="en_US.UTF-8"
 fi
 
+if [[ -z "${_flag_base}" ]]; then
+	_e_report_back "You must choose a base if your run gse without main menu. Aborting..."
+	_e_report_back "See man 1 gse for base options."
+	die "Aborting actions..."
+fi
+echo "$@"
 # STAGE A
 # CHECK POSITIONAL PARAMETERS
 inspector "$@"
@@ -18,7 +24,6 @@ echo -e "[\e[32m*\e[0m] \e[34mInitializing\e[0m"
 source "${CWORKDIR}/etc/gentoo.conf" >/dev/null 2>&1 \
 && echo -e "[\e[32m*\e[0m] \e[35mExporting variables\e[0m" \
 || { echo -e "[\e[31m*\e[0m] \e[35mExporting variables\e[0m"; echo -e "\e[31mAborting\e[0m..."; sleep 2; return 1; }
-
 
 # PART A FUNDAMENTALS
 _part_a() {
@@ -41,49 +46,73 @@ _part_a() {
 	case "${_flag_base}" in
 		catalyst)
 
+			if grep -q '\-gseed' "${CLOCALLG}/doscripts"; then
+				_e_report_back "Sourcing scripts before gseed"
+				_do_rs '\-gseed'
+			fi
+
 			if _seed_net "$@"; then
 				sinit_flow_monitor "SEED"
 			fi
 
-			if [[ "$(awk -F '=' '/CATALYST/{ print $2 }' < "${CLOCALLG}/sinprog")" == 0 ]] || echo "$@" | grep -q 'force'; then
-				_callying_catalyst "$@" || die "Catalyst failed"
-				sinit_flow_monitor "CATALYST"
+			if grep -q '\+gseed' "${CLOCALLG}/doscripts"; then
+				_e_report_back "Sourcing scripts after gseed"
+				_do_rs '\+gseed'
+			fi
+
+			if grep -q '\-gcat' "${CLOCALLG}/doscripts"; then
+				_e_report_back "Sourcing scripts before catalyst"
+				_do_rs '\-gcat'
+			fi
+
+			if echo "${_lawful_args[@]}" | grep -q 'gcat'; then
+				_e_report_back "Catalyst: Lawful entry detected, proceeding..."
 			else
-				if echo "${_lawful_args[@]}" | grep -q 'gcat'; then
-					_e_report_back "Catalyst: Lawful entry detected, proceeding..."
-				else
+				if [[ "$(awk -F '=' '/CATALYST/{ print $2 }' < "${CLOCALLG}/sinprog")" == 0 ]] || echo "$@" | grep -q 'force' || echo "${_enforce_args[@]}" | grep -q 'gcat'; then
 					if echo "${_enforce_args[@]}" | grep -q 'gcat'; then
 						_e_report_back "Catalyst: Enforce entry detected, forcing..."
 						_callying_catalyst "$@" "force" || die
 						sinit_flow_monitor "CATALYST"
 					else
-						if _repeat_subpart "Catalyst" "configured"; then
-							_callying_catalyst "$@" || die
-						else	
-							echo -e "\e[33mProceeding with extraction...\e[0m"
-						fi
+						_callying_catalyst "$@" || die
+						sinit_flow_monitor "CATALYST"
+					fi
+				else 
+					if _repeat_subpart "Catalyst" "configured"; then
+						_callying_catalyst "$@" || die
+					else	
+						echo -e "\e[33mProceeding with extraction...\e[0m"
 					fi
 				fi
 			fi
 
-		
-			if [[ "$(awk -F '=' '/EXTRACTION/{ print $2 }' < "${CLOCALLG}/sinprog")" == 0 ]] || echo "$@" | grep -q 'force'; then
-				_extracting_catalyst "$@" || die "Extraction failed"
-				sinit_flow_monitor "EXTRACTION"
+			if grep -q '\+gcat' "${CLOCALLG}/doscripts"; then
+				_e_report_back "Sourcing scripts after catalyst"
+				_do_rs '\+gcat'
+			fi
+
+			if grep -q '\-gextr' "${CLOCALLG}/doscripts"; then
+				_e_report_back "Sourcing scripts before extraction"
+				_do_rs '\-gextr'
+			fi
+
+			if echo "${_lawful_args[@]}" | grep -q 'gextr'; then
+				_e_report_back "Extraction: Lawful entry detected, proceeding..."
 			else
-				if echo "${_lawful_args[@]}" | grep -q 'extr'; then
-					_e_report_back "Extraction: Lawful entry detected, proceeding..."
-				else
-					if echo "${_enforce_args[@]}" | grep -q 'extr'; then
+				if [[ "$(awk -F '=' '/EXTRACTION/{ print $2 }' < "${CLOCALLG}/sinprog")" == 0 ]] || echo "$@" | grep -q 'force'; then
+					if echo "${_enforce_args[@]}" | grep -q 'gextr'; then
 						_e_report_back "Extraction: Enforce entry detected, forcing..."
 						_extracting_catalyst "$@" "force" || die
 						sinit_flow_monitor "EXTRACTION"
 					else
-						if _repeat_subpart "Extraction" "completed"; then
-							_extracting_catalyst "$@" || die
-						else
-							echo -e "\e[33mProceeding to Part: B...\e[0m"
-						fi
+						_extracting_catalyst "$@" || die
+						sinit_flow_monitor "EXTRACTION"
+					fi
+				else
+					if _repeat_subpart "Extraction" "completed"; then
+						_extracting_catalyst "$@" || die
+					else
+						echo -e "\e[33mProceeding to Part: B...\e[0m"
 					fi
 				fi
 			fi
@@ -92,60 +121,93 @@ _part_a() {
 			unset TARGETNAME
 			unset TARGETPATH
 			unset TARGETSTAMP
-			;;
+
+			if grep -q '\+gextr' "${CLOCALLG}/doscripts"; then
+				_e_report_back "Sourcing scripts after extraction"
+				_do_rs '\+gextr'
+			fi;;
+
 		precomp)
+			
+			if grep -q '\-gseed' "${CLOCALLG}/doscripts"; then
+				_e_report_back "Sourcing scripts before gseed"
+				_do_rs '\-gseed'
+			fi
 
 			if _seed_net "$@"; then
 				sinit_flow_monitor "SEED"
 			fi
 
-			if [[ "$(awk -F '=' '/PRECOMP/{ print $2 }' < "${CLOCALLG}/sinprog")" == 0 ]] || echo "$@" | grep -q 'force'; then
-				_workdir_check "${CDISTDIR}/dists/stage3-${ARCH}-latest.tar.bz2" \
-				"${CDISTDIR}/workdir-precomp" "$@" || die
+			if grep -q '\+gseed' "${CLOCALLG}/doscripts"; then
+				_e_report_back "Sourcing scripts after gseed"
+				_do_rs '\+gseed'
+			fi
+
+			if grep -q '\-gprec' "${CLOCALLG}/doscripts"; then
+				_e_report_back "Sourcing scripts before precomp extraction"
+				_do_rs '\-gprec'
+			fi
+
+			if echo "${_lawful_args[@]}" | grep -q 'gprec'; then
+				_e_report_back "Precomp: Lawful entry detected, proceeding..."
 			else
-				if echo "${_lawful_args[@]}" | grep -q 'gprec'; then
-					_e_report_back "Precomp: Lawful entry detected, proceeding..."
-				else
+				if [[ "$(awk -F '=' '/PRECOMP/{ print $2 }' < "${CLOCALLG}/sinprog")" == 0 ]] || echo "$@" | grep -q 'force'; then
 					if echo "${_enforce_args[@]}" | grep -q 'gprec'; then
 						_e_report_back "Precomp: Enforce entry detected, forcing..."
-						_extracting_catalyst "$@" "force" || die
+						_workdir_check "${CDISTDIR}/dists/stage3-${ARCH}-latest.tar.bz2" \
+						"${CDISTDIR}/workdir-precomp" "$@" "force" || die
+						sinit_flow_monitor "PRECOMP"
 					else
-						if _repeat_subpart "Precomp Extraction" "completed"; then
-							_workdir_check
-							"${CDISTDIR}/dists/stage3-${ARCH}-latest.tar.bz2" \
-							"${CDISTDIR}/workdir-precomp" "$@"
-						else
-							echo -e "\e[33mProceeding to Part: B...\e[0m"
-						fi
+						_workdir_check "${CDISTDIR}/dists/stage3-${ARCH}-latest.tar.bz2" \
+						"${CDISTDIR}/workdir-precomp" "$@" || die
+						sinit_flow_monitor "PRECOMP"
+					fi
+				else
+					if _repeat_subpart "Precomp Extraction" "completed"; then
+						_workdir_check "${CDISTDIR}/dists/stage3-${ARCH}-latest.tar.bz2" \
+						"${CDISTDIR}/workdir-precomp" "$@" || die
+					else
+						echo -e "\e[33mProceeding to Part: B...\e[0m"
 					fi
 				fi
+			fi
+			
+			if grep -q '\+gprec' "${CLOCALLG}/doscripts"; then
+				_e_report_back "Sourcing scripts after precomp extraction"
+				_do_rs '\+gprec'
 			fi;;
 	esac
 }
 
+if grep -q '\-gparta' "${CLOCALLG}/doscripts"; then
+	_e_report_back "Sourcing scripts before Part: A"
+	_do_rs '\-gparta'
+fi
 
-if [[ "$(awk -F '=' '/PARTA/{ print $2 }' < "${CLOCALLG}/sinprog")" == 0 || -n $(echo "${_flag_force_new}") ]] || echo "${_enforce_args[@]}" | grep -q 'gparta'; then
-	if 	[[ -n $(echo "${_flag_force_new}") ]] || echo "${_enforce_args[@]}" | grep -q 'gparta'; then
-		_part_a "$@" "force" || die
-		sinit_flow_monitor "PARTA"
-	else
-		_part_a "$@" || die
-		sinit_flow_monitor "PARTA"
-	fi
-else
-	if echo "${_lawful_args[@]}" | grep -q 'gparta'; then
-		_e_report_back "Lawful entry detected on parta, proceeding..."
-	else		
-		if echo "${_enforce_args[@]}" | grep 'gparta'; then
-			_e_report_back "Enforce entry detected on parta, forcing..."
+if echo "${_lawful_args[@]}" | grep -q 'gparta'; then
+	_e_report_back "Lawful entry detected on parta, proceeding..."
+else	
+	if [[ "$(awk -F '=' '/PARTA/{ print $2 }' < "${CLOCALLG}/sinprog")" == 0 || -n "${_flag_force_new}" ]] || echo "${_enforce_args[@]}" | grep -q 'gparta'; then
+		if 	[[ -n "${_flag_force_new}" ]] || echo "${_enforce_args[@]}" | grep -q 'gparta'; then
+			_e_report_back "Force entry detected on part a, forcing..."
 			_part_a "$@" "force" || die
 			sinit_flow_monitor "PARTA"
 		else
-			if repeat_parta "A"; then
-				_part_a "$@"
-			fi
+			_part_a "$@" || die
+			sinit_flow_monitor "PARTA"
+		fi
+	else
+		if repeat_part "A"; then
+			_part_a "$@"
+		else
+			_e_report_back "Proceeding with part b"
 		fi
 	fi
+fi
+
+if grep -q '\+gparta' "${CLOCALLG}/doscripts"; then
+	_e_report_back "Sourcing scripts after Part: A"
+	_do_rs '\+gparta'
 fi
 
 case "${_flag_base}" in
@@ -162,33 +224,70 @@ echo "==========================================================================
 _am_i_root "$UID" && echo -e "[\e[32m*\e[0m] Requesting root privileges" \
 || { echo -e "[\e[31m*\e[0m] Requesting root privileges"; exit 1; }
 
+_part_b() {
+	if _prepare_chroot "$@"; then
+		if grep -q '\-gclean' "${CLOCALLG}/doscripts"; then
+			_e_report_back "Sourcing scripts before cleanup"
+			_do_rs '\-gclean'
+		fi		
+				
+		_clean_target "$@" || die
+
+		if grep -q '\+gclean' "${CLOCALLG}/doscripts"; then
+			_e_report_back "Sourcing scripts after cleanup"
+			_do_rs '\+gclean'
+		fi
+
+		sinit_flow_monitor "PARTB"
+	else
+		die "Cleaning failed"
+	fi
+}
+
+if grep -q '\-gpartb' "${CLOCALLG}/doscripts"; then
+	_e_report_back "Sourcing scripts before Part: B"
+	_do_rs '\-gpartb'
+fi
+
+if echo "${_lawful_args[@]}" | grep -q 'gpartb'; then
+	_e_report_back "Lawful entry detected on part b, proceeding..."
+else	
+	if [[ "$(awk -F '=' '/PARTB/{ print $2 }' < "${CLOCALLG}/sinprog")" == 0 || -n "${_flag_start_new}" ]] || echo "${_enforce_args[@]}" | grep 'gpartb'; then
+		if 	[[ -n "${_flag_force_new}" ]] || echo "${_enforce_args[@]}" | grep -q 'gparta'; then
+			_e_report_back "Force entry detected on partb, forcing..."
+			_part_b "${BWORKDIR}" "$@" "${_flag_base}" 'cforce'
+		else
+			_part_b "${BWORKDIR}" "$@" "${_flag_base}"
+		fi
+	else
+		if repeat_part "B"; then
+			_part_b "${BWORKDIR}" "$@" "${_flag_base}"
+		else
+			_e_report_back "Proceeding..."
+		fi
+	fi
+fi
+
+if grep -q '\+gpartb' "${CLOCALLG}/doscripts"; then
+	_e_report_back "Sourcing scripts after Part: B"
+	_do_rs '\+gpartb'
+fi
+
+umount -l "${BWORKDIR}/"*
+umount -l "${BWORKDIR}/"*
+umount -l "${BWORKDIR}/"*
+umount -l "${BWORKDIR}/"*
+umount -l "${BWORKDIR}/"*
+
 TARGETSTAMP="$(grep 'version_stamp' "${CCONFDIR}/system/catalyst/stage3.spec" \
 | sed '/^#/ d' | awk -F ' ' '{ print $2 }' | sed  -e "s_\"__g")"
 
-if [[ -n "${_flag_start_new}" ]] || echo "${_enforce_args[@]}" | grep 'gpartb'; then
-	if _prepare_chroot "${BWORKDIR}" "$@" 'cforce'; then
-		_clean_target "${BWORKDIR}" "$@" || die
-	else
-		die "Cleaning failed"
-	fi
-else
-	if _prepare_chroot "${BWORKDIR}" "$@"; then
-		_clean_target "${BWORKDIR}" "$@" || die
-	else
-		die "Cleaning failed"
-	fi
-fi
-umount -l "${BWORKDIR}/"*
-umount -l "${BWORKDIR}/"*
-umount -l "${BWORKDIR}/"*
-umount -l "${BWORKDIR}/"*
-umount -l "${BWORKDIR}/"*
 SUBBUILD=0
 GVEX="${GSEVER}.${SUBBUILD}"
 while true; do
 	if ! ls "${CDISTDIR}/stage3-amd64-${GVEX}.tar.bz2" >/dev/null 2>&1; then
 		(cd "${BWORKDIR}"
-		tar -cjpP --ignore-failed-read "${CDISTDIR}/stage3-amd64-${GVEX}.tar.bz2" . >/dev/null 2>&1; ) \
+		tar -cjpP --ignore-failed-read "${CDISTDIR}/stage3-amd64-${TARGETSTAMP}-${GVEX}.tar.bz2" . >/dev/null 2>&1; ) \
 		&& { _o_report_back "Archived" && echo -e "\e[34mYou can find your system @ ${CDISTDIR}\e[0m"
 		echo -e "\e[34mWith version extension: ${GVEX}\e[0m"; } \
 		|| die "Failed"
@@ -202,7 +301,7 @@ done
 exit
 
 gpg --armor --export email > "${FINALDIST}/key.asc" # THIS WILL BE ADDED TO THE HOSTS
-gpg --detach-sign -o ${GSE_VER}.gpg "${FINALDIST}/${IMAGE}"
+gpg --detach-sign -o "${GSE_VER}".gpg "${FINALDIST}/${IMAGE}"
 #rm -rf "$1/sinit.d"
 unset CATDIR
 unset TARGETPATH
