Created main-builders script

diff --git a/scripts/sinit b/scripts/sinit
--- a/scripts/sinit
+++ b/scripts/sinit
@@ -1,26 +1,30 @@
 #!/bin/bash
 
+LC_COLLATE=C
+
+# MAIN BUILDER
+
 # CHECK FOR THE POSITIONAL PARAMETERS AND BAILOUT IF THEY ARE MISSING
 [[ -z "${DISTDIR}" ]] && print_inf 4 && return 1
-echo "Checking for dependencies"
-lcreq || exit 1
-echo "Initializing..."
+echo -e "\e[34mChecking for dependencies\e[0m"
+#lcreq || exit 1
+echo -e "[\e[32m*\e[0m] \e[34mInitializing\e[0m"
 sleep 0.5
 
 # ALL ESSENTIAL VARIABLES FOR THE DOWNLOAD AND AUTHENTICATION PROCESS
-source "${WORKDIR}/etc/gentoo.conf" >/dev/null 2>&1 && { echo -e "[\e[32m*\e[0m] Exporting variables" ;} \
-|| { echo -e "[\e[31m*\e[0m] Exporting variables"; echo "Aborting..."; return 1; }
+source "${WORKDIR}/etc/gentoo.conf" >/dev/null 2>&1 && { echo -e "[\e[32m*\e[0m] \e[35mExporting variables\e[0m" ;} \
+|| { echo -e "[\e[31m*\e[0m] \e[35mExporting variables\e[0m"; echo -e "[\e[31mAborting\e[0m..."; sleep 2; return 1; }
 
 export GENTOOKEY="$(lynx -dump ${SIGNING_KEY} |  grep "(4096-bit RSA)" | head -1 | awk -F '(' '{ print $1}')"
 export "GENTOOKEY"
 export GENTOOLATEST="$DIST/$(wget -q -O- "${DIST}/latest-stage3-$ARCH.txt" | tail -n 1 | awk -F ' ' '{ print $1 }')"
-STAGE3TB=$(wget -q -O- "${DIST}/latest-stage3-$ARCH.txt" | tail -n 1 | awk -F ' ' '{ print $1 }' | awk -F '/' '{ print $2 }')
+export STAGE3TB=$(wget -q -O- "${DIST}/latest-stage3-$ARCH.txt" | tail -n 1 | awk -F ' ' '{ print $1 }' | awk -F '/' '{ print $2 }')
 export GENTOOLATESTASC="$DIST/$(wget -q -O- "${DIST}/latest-stage3-$ARCH.txt" | tail -n 1 | awk -F ' ' '{ print $1 }').DIGESTS.asc"
 
 # PROMPT TO CONTINUE OR START ANEW
 if [[ "$(awk -F '=' '/KEY/{ print $2 }' <"${LOCALLG}/sinprog")" == 1 ]]; then
 while true; do
-clear; echo "Do you want to continue from last time?"
+clear; echo -e "\e[32mDo you want to continue from last time?\e[0m"
 read -p "Answer Yes or START NEW: " yn
 echo 
 case ${yn} in
@@ -41,45 +45,47 @@ esac
 done
 fi
 
-# PART A FLOW CHECK
+keep_out(){
+# PART A FUNDAMENTALS
 [[ "$(awk -F '=' '/PARTA/{ print $2 }' <"${LOCALLG}/sinprog")" == 0 ]] \
-&& clear && echo "PART:A Required files" && sleep 2
+&& clear && echo -e "\e[35mPART:A Fundamentals\e[0m" && sleep 2
 
 # FETCH THE KEYS FOR THE CRYPTOGRAPHIC AUTHENTICATION
-if [[ "$(awk -F '=' '/KEY/{ print $2 }' <"${LOCALLG}/sinprog")" == 0 ]]; then
-echo "Fetching Key"
+ if [[ "$(awk -F '=' '/KEY/{ print $2 }' <"${LOCALLG}/sinprog")" == 0 ]]; then
+
 [[ -z "${GENTOOKEY}" ]] && print_inf 4 && return 1
 
 gpg --keyserver hkps.pool.sks-keyservers.net --recv-keys >/dev/null 2>&1 ${GENTOOKEY} \
-&& print_inf 1 || { print_inf 2; return 1; }
+&& echo -e "[\e[32m*\e[0m]\e[32m Fetching Key\e[0m" \
+|| { echo -e "[\e[31m*\e[0m]\e[31m Fetching Key\e[0m"; return 1; }
 sinit_mon 1
 fi
-unset KEY
 
 # DOWNLOAD THE LATEST STAGE3 TARBALL TO ACT AS THE CATALYST'S SEED S3T
 if [[ "$(awk -F '=' '/WGETST3/{ print $2 }' <"${LOCALLG}/sinprog")" == 0 ]]; then
-echo "Getting ${STAGE3TB}"
+
 [[ -z "${GENTOOLATEST}" || -z "${GENTOOLATESTASC}" ]] && print_inf 4 && return 1
 
 mkdir -p "${DISTDIR}/${STAGE3TB}" "${DISTDIR}/dists"
 
 if [[ ! -e "${DISTDIR}/dists/${STAGE3TB}" ]]; then
+echo -e "[\e[32m*\e[0m] Getting \e[34m${STAGE3TB}\e[0m"
 wget -c --progress=dot -P "${DISTDIR}/dists" "${GENTOOLATEST}" \
 && print_inf 1 || { print_inf 2; return 1; }
+elif [[ -e "${DISTDIR}/dists/${STAGE3TB}" ]]; then
+echo -e "[\e[32m*\e[0m] Located \e[34m${STAGE3TB}\e[0m"
 fi
 
-echo "Getting ${GENTOOLATESTASC}"
 if [[ ! -e "${DISTDIR}/dists/${GENTOOLATESTASC}" ]]; then
 wget -c --progress=dot -P "${DISTDIR}/dists" "${GENTOOLATESTASC}" >/dev/null 2>&1 \
-&& echo -e "[\e[32m*\e[0m] Getting ${GENTOOLATEST}" \
-|| echo -e "[\e[31m*\e[0m] Getting ${GENTOOLATEST}"
+&& echo -e "[\e[32m*\e[0m] Getting \e[34m${GENTOOLATEST}\e[0m" \
+|| echo -e "[\e[31m*\e[0m] \e[31mFAILD\e[0m: Getting \e[34m${GENTOOLATEST}\e[0m"
 fi
 
-echo "Getting ${GENTOOLATEST}.DIGESTS"
 if [[ ! -e "${DISTDIR}/dists/${GENTOOLATEST}.DIGESTS" ]]; then
 wget -c --progress=dot -P "${DISTDIR}/dists" "${GENTOOLATEST}.DIGESTS" >/dev/null 2>&1 \
-&& echo -e "[\e[32m*\e[0m] Getting ${GENTOOLATEST}.DIGESTS" \
-|| echo -e "[\e[31m*\e[0m] Getting ${GENTOOLATEST}.DIGESTS"
+&& echo -e "[\e[32m*\e[0m] Getting \e[34m${GENTOOLATEST}.DIGESTS\e[0m" \
+|| echo -e "[\e[31m*\e[0m] \e[31mFAILD\e[0m: Getting $\e[34m${GENTOOLATEST}.DIGESTS\e[0m"
 fi
 
 sinit_mon 2
@@ -89,28 +95,35 @@ unset WGETST3
 # VERIFY THE AUTHENTICATION OF THE DOWNLOADED FILES
 if [[ "$(awk -F '=' '/VERIFICATION/{ print $2 }' <"${LOCALLG}/sinprog")" == 0 ]]; then
 gpg --verify "${DISTDIR}/dists/${STAGE3TB}.DIGESTS.asc" >/dev/null 2>&1 \
-&& echo -e "[\e[32m*\e[0m] Verifying the cryptographic signature" \
-|| echo -e "[\e[31m*\e[0m] Verifying the cryptographic signature"
+&& echo -e "[\e[32m*\e[0m] Verifying \e[35mcryptographic signature\e[0m" \
+|| echo -e "[\e[31m*\e[0m] \e[31mFAILD\e[0m: Verifying \e[31mcryptographic signature\e[0m"
 
 [[ $(grep -A 1 -i sha512 "${DISTDIR}/dists/${STAGE3TB}.DIGESTS.asc" | head -n 2 |grep stage3 | awk -F ' ' '{ print $1 }') \
-== $(sha512sum "${DISTDIR}/dists/${STAGE3TB}" |  awk -F ' ' '{ print $1 }') ]] && echo -e "[\e[32m*\e[0m] Verifying sha512sums" \
-|| echo -e "[\e[31m*\e[0m] Verifying sha512sums"
+== $(sha512sum "${DISTDIR}/dists/${STAGE3TB}" |  awk -F ' ' '{ print $1 }') ]] && echo -e "[\e[32m*\e[0m] Verifying \e[35msha512sums\e[0m" \
+|| echo -e "[\e[31m*\e[0m] \e[31mFAILD\e[0m: Verifying \e[31msha512sums\e[0m"
 sinit_mon 3
 fi
 unset VERIFICATION
-
+}
 # CATALYST BEGINS HERE
 
-cp "${DISTDIR}/dists/${STAGE3TB}" "${DISTDIR}/dists/catalyst/builds/defaults/${GSE_VER}.tar.bz2"
-init_stage3_seq
+echo -e "\e[34mCallling Catalyst\e[0m"
+sleep 0.5
+
+if init_stage3_seq; then
+sinit_mon 7 && echo "CATALYST=0" > "${LOCALLG}/tborigin"
+else
+sinit_mon 8 && echo "CATALYST=1" > "${LOCALLG}/tborigin"
+fi
 unset CATADIR
 unset CATPORTDIR
 unset CATPORTCACHEDIR
 unset CATLOGDIR
 unset CATDISTDIR
 # CATALYST ENDS HERE
+exit
+if cp "${CATADIR}/builds/defaults/stage3-${ARCH}-${GSE_VER}.tar.bz2"; then echo "Stage3 tarball built"; echo "Extracting"; fi
 
-cp "${DISTDIR}/dists/catalyst/builds/defaults/stage3-${ARCH}-${GSE_VER}.tar.bz2"
 # Extract the tarball
 if [[ "$(awk -F '=' '/EXTRACTION/{ print $2 }' < "${LOCALLG}/sinprog")" == 0 ]]; then
 echo "Extracting tarball"
@@ -126,9 +139,9 @@ sinit_mon 4
 fi
 unset EXTRACTION
 
-
+# PART B
 [[ "$(awk -F '=' '/PARTB/{ print $2 }' <"${LOCALLG}/sinprog")" == 0 ]] \
-&& clear && echo "PART:B Preparing to enter the new system" && sleep 2
+&& clear && echo -e "\e[35mPART:B Preparing to enter the new system\e[0m" && sleep 2
 
 # Root check function
 amiroot() {
