Major update

diff --git a/scripts/sinit b/scripts/sinit
--- a/scripts/sinit
+++ b/scripts/sinit
@@ -1,24 +1,73 @@
 #!/bin/bash
 
 LC_COLLATE=C
-LC_ALL="en_US.UTF-8"
+#LC_ALL="en_US.UTF-8"
 LC_CTYPE="en_US.UTF-8"
 
 # MAIN BUILDER
+dep_c_f() {
+if [[ "${CREL}" == "Gentoo" ]]; then
+echo -e "\e[33mHost system:\e[0m \e[35m${CREL}\e[0m"
+echo -e "\e[33mBefore you begin, it is strongly recommended to make a\e[0m \e[35mruntime dependency\e[0m \e[33mcheck on the host machine\e[0m"
+echo -e "\e[33mThis check is a simple\e[0m \e[35meix\e[0m \e[33m--installed foo check, which will be very fast and also verify\e[0m"
+echo -e "\e[33mthat during the process, nothing unexpected will occur\e[0m"
+echo -e "\e[33mIf\e[0m \e[35meix\e[0m \e[33mis not installed, do no worry, it will get installed\e[0m"
+echo
+while true; do
+	read -rp "Check dependencies? Y/N: " YN
+	case "${YN:-n}" in
+		[yY])
+			echo -e "\e[34mChecking for dependencies\e[0m"
+			lcreq 1 || exit 1
+			break;;
+		[nN])
+			echo "If you have not run a dependency check before, please abort"
+			for i in {1..0}; do
+   				sleep 1
+   				printf "\r $i"
+			done
+			break;;
+	esac
+done
+unset YN
+else
+echo -e "\e[33mHost system:\e[0m \e[33m${CREL}\e[0m"
+echo -e "\e[33mBefore you begin, it is strongly recommended to make a\e[0m \e[35mruntime dependency\e[0m \e[33mcheck on the host machine\e[0m"
+echo -e "\e[33mIf the all runtime dependencies are located, the process will continue, otherwise this window will exit. and expect you to manually install them\e[0m"
+echo -e "\e[33mSince only Gentoo is officially upported, it is expected to manually install any missing dependencies\e[0m"
+while true; do
+	read -rp "Check dependencies? Y/N: " YN
+	case "${YN:-n}" in
+		[yY])
+			echo -e "\e[34mChecking for dependencies\e[0m"
+			lcreq 2 || exit 1
+			break;;
+		[nN])
+			echo "If you have not run a dependency check before, please abort"
+			for i in {1..0}; do
+   				sleep 1
+   				printf "\r $i"
+			done
+			break;;
+	esac
+done
+fi	
+}
+
+dep_c_f
 
 # CHECK FOR THE POSITIONAL PARAMETERS AND BAILOUT IF THEY ARE MISSING
-[[ -z "${DISTDIR}" ]] && print_inf 4 && return 1
+[[ -z "${CDISTDIR}" ]] && print_inf 4 && return 1
 echo "============================================================================"
-echo -e "\e[34mChecking for dependencies\e[0m"
-#lcreq || exit 1
 echo -e "[\e[32m*\e[0m] \e[34mInitializing\e[0m"
 sleep 0.5
 
 # ALL ESSENTIAL VARIABLES FOR THE DOWNLOAD AND AUTHENTICATION PROCESS
-source "${WORKDIR}/etc/gentoo.conf" >/dev/null 2>&1 && { echo -e "[\e[32m*\e[0m] \e[35mExporting variables\e[0m"
+source "${CWORKDIR}/etc/gentoo.conf" >/dev/null 2>&1 && { echo -e "[\e[32m*\e[0m] \e[35mExporting variables\e[0m"
 echo "============================================================================"; } \
 || { echo -e "[\e[31m*\e[0m] \e[35mExporting variables\e[0m"; echo -e "[\e[31mAborting\e[0m..."; sleep 2; return 1; }
 if ping -c 3 www.gentoo.org >/dev/null 2>&1; then
+NONETNEED=0
 export GENTOOKEY="$(lynx -dump ${SIGNING_KEY} |  grep "(4096-bit RSA)" | head -1 | awk -F '(' '{ print $1}')"
 export "GENTOOKEY"
 export GENTOOLATEST="$DIST/$(wget -q -O- "${DIST}/latest-stage3-$ARCH.txt" | tail -n 1 | awk -F ' ' '{ print $1 }')"
@@ -27,41 +76,46 @@ export GENTOOLATESTASC="$DIST/$(wget -q -O- "${DIST}/latest-stage3-$ARCH.txt" | 
 else
 echo -e "[\e[31m*\e[0m] \e[34mConnection could not be established\e[0m"
 echo -e "[\e[31m*\e[0m] \e[35mSearching for local\e[0m"
-export STAGE3TB=$(sha512sum -c "${DISTDIR}/dist/stage3-amd64-latest.sha512" \
-| awk -F ' ' '{ print $1 }' | awk -F ':' '{ print $1 }')
+export STAGE3TB="stage3-${ARCH}-latest.tar.bz2"
+export GENTOOLATESTASC="${STAGE3}.DIGESTS.asc"
+export NONETNEED=1
 fi
 
 # PROMPT TO CONTINUE OR START ANEW
-if [[ "$(awk -F '=' '/KEY/{ print $2 }' <"${LOCALLG}/sinprog")" == 1 ]]; then
+if [[ "$(awk -F '=' '/KEY/{ print $2 }' <"${CLOCALLG}/sinprog")" == 1 ]]; then
 while true; do
 clear; echo -e "\e[32mDo you want to continue from last time?\e[0m"
-read -p "Answer Yes or START NEW: " yn
+read -p "Answer Yes or START NEW: " YN
 echo 
-case ${yn} in
+case "${YN:-n}" in
 	[Yy][eE][sS]|[yY])
 		break;;
 	"START NEW")
 		# CHECK IF THE PSEUDOS ARE MOUNTED, ATTEMPT TO UNMOUNT AND BAILOUT IF UNABLE TO
 		[[ -n $(grep 'dist.d/stage3' /proc/mounts | awk -F ' ' '{ print $1 }') ]] \
-		&& { umount -l "${DISTDIR}/${STAGE3TB}"/* >/dev/null 2>&1 && sleep 2 \
-		&& umount -l "${DISTDIR}/${STAGE3TB}"/* >/dev/null 2>&1 \
+		&& { umount -l "${CDISTDIR}/${STAGE3TB}"/* >/dev/null 2>&1 && sleep 2 \
+		&& umount -l "${CDISTDIR}/${STAGE3TB}"/* >/dev/null 2>&1 \
 		&& [[ -z $(grep 'dist.d/stage3' /proc/mounts | awk -F ' ' '{ print $1 }') ]] && exit 1; }
 
-		sinit_mon 5 && sed -i -e 's/1/0/g' "${WORKDIR}/scripts/chroot_scripts/chsinprog"; break;;
+		sinit_mon 5 && sed -i -e 's/1/0/g' "${CWORKDIR}/scripts/chroot_scripts/chsinprog"; break;;
 	* ) echo "Wrong answer";;
 esac
 done
 fi
 
+unset YN
+
 seed_f(){
 # PART A FUNDAMENTALS
-[[ "$(awk -F '=' '/PARTA/{ print $2 }' <"${LOCALLG}/sinprog")" == 0 ]] \
+[[ "$(awk -F '=' '/PARTA/{ print $2 }' <"${CLOCALLG}/sinprog")" == 0 ]] \
 && clear; echo "============================================================================"
 echo -e "\e[35mPART:A Fundamentals\e[0m"
 echo "============================================================================"
 
+if [[ "${NONETNEED}" != 1 ]]; then
+
 # FETCH THE KEYS FOR THE CRYPTOGRAPHIC AUTHENTICATION
-if [[ "$(awk -F '=' '/KEY/{ print $2 }' <"${LOCALLG}/sinprog")" == 0 ]]; then
+if [[ "$(awk -F '=' '/KEY/{ print $2 }' <"${CLOCALLG}/sinprog")" == 0 ]]; then
 
 [[ -z "${GENTOOKEY}" ]] && print_inf 4 && return 1
 
@@ -72,51 +126,58 @@ sinit_mon 1
 fi
 
 # DOWNLOAD THE LATEST STAGE3 TARBALL TO ACT AS THE CATALYST'S SEED S3T
-if [[ "$(awk -F '=' '/WGETST3/{ print $2 }' <"${LOCALLG}/sinprog")" == 0 ]]; then
+if [[ "$(awk -F '=' '/WGETST3/{ print $2 }' <"${CLOCALLG}/sinprog")" == 0 ]]; then
 
 [[ -z "${GENTOOLATEST}" || -z "${GENTOOLATESTASC}" ]] && print_inf 4 && return 1
 
-mkdir -p "${DISTDIR}/${STAGE3TB}" "${DISTDIR}/dists" \
-&& if [[ ! -e "${DISTDIR}/dists/${STAGE3TB}" ]]; then
+mkdir -p "${CDISTDIR}/dists" \
+&& if [[ ! -e "${CDISTDIR}/dists/stage3-${ARCH}-latest.tar.bz2" ]]; then
 echo -e "[\e[32m*\e[0m] Getting \e[34m${STAGE3TB}\e[0m"
-wget -c --progress=dot -P "${DISTDIR}/dists" "${GENTOOLATEST}" \
+wget -c -O "${CDISTDIR}/dists/stage3-${ARCH}-latest.tar.bz2" "${GENTOOLATEST}" \
 && print_inf 1 || { print_inf 2; return 1; }
-elif [[ -e "${DISTDIR}/dists/${STAGE3TB}" ]]; then
+elif [[ -e "${CDISTDIR}/dists/stage3-${ARCH}-latest.tar.bz2" ]]; then
 echo -e "[\e[32m*\e[0m] Located \e[34m${STAGE3TB}\e[0m"
 fi \
-&& if [[ ! -e "${DISTDIR}/dists/${GENTOOLATESTASC}" ]]; then
-wget -c --progress=dot -P "${DISTDIR}/dists" "${GENTOOLATESTASC}" >/dev/null 2>&1 \
+&& if [[ ! -e "${CDISTDIR}/dists/stage3-${ARCH}-latest.tar.bz2.DIGESTS.asc" ]]; then
+wget -c -O "${CDISTDIR}/dists/stage3-${ARCH}-latest.tar.bz2.DIGESTS.asc" "${GENTOOLATESTASC}" >/dev/null 2>&1 \
 && echo -e "[\e[32m*\e[0m] Getting \e[34m${GENTOOLATEST}\e[0m" \
 || echo -e "[\e[31m*\e[0m] \e[31mFAILD\e[0m: Getting \e[34m${GENTOOLATEST}\e[0m"
 fi \
-&& if [[ ! -e "${DISTDIR}/dists/${GENTOOLATEST}.DIGESTS" ]]; then
-wget -c --progress=dot -P "${DISTDIR}/dists" "${GENTOOLATEST}.DIGESTS" >/dev/null 2>&1 \
+&& if [[ ! -e "${CDISTDIR}/dists/stage3-${ARCH}-latest.tar.bz2.DIGESTS" ]]; then
+wget -c -O "${CDISTDIR}/dists/stage3-${ARCH}-latest.tar.bz2.DIGESTS" "${GENTOOLATEST}.DIGESTS" >/dev/null 2>&1 \
 && echo -e "[\e[32m*\e[0m] Getting \e[34m${GENTOOLATEST}.DIGESTS\e[0m" \
 || echo -e "[\e[31m*\e[0m] \e[31mFAILD\e[0m: Getting $\e[34m${GENTOOLATEST}.DIGESTS\e[0m"
 fi \
-&& sha512sum "${DISTDIR}/dists/${STAGE3TB}" > "${DISTDIR}/dists/stage3-${ARCH}-latest.tar.bz2.sha512"
+&& sha512sum "${CDISTDIR}/dists/stage3-${ARCH}-latest.tar.bz2" > "${CDISTDIR}/dists/stage3-${ARCH}-latest.tar.bz2.sha512"
 
 sinit_mon 2
 fi
 unset WGETST3
 
 # VERIFY THE AUTHENTICATION OF THE DOWNLOADED FILES
-if [[ "$(awk -F '=' '/VERIFICATION/{ print $2 }' <"${LOCALLG}/sinprog")" == 0 ]]; then
-gpg --verify "${DISTDIR}/dists/${STAGE3TB}.DIGESTS.asc" >/dev/null 2>&1 \
+if [[ "$(awk -F '=' '/VERIFICATION/{ print $2 }' <"${CLOCALLG}/sinprog")" == 0 ]]; then
+gpg --verify "${CDISTDIR}/dists/stage3-${ARCH}-latest.tar.bz2.DIGESTS.asc" >/dev/null 2>&1 \
 && echo -e "[\e[32m*\e[0m] Verifying \e[35mcryptographic signature\e[0m" \
 || echo -e "[\e[31m*\e[0m] \e[31mFAILD\e[0m: Verifying \e[31mcryptographic signature\e[0m"
 
-[[ $(grep -A 1 -i sha512 "${DISTDIR}/dists/${STAGE3TB}.DIGESTS.asc" | head -n 2 |grep stage3 | awk -F ' ' '{ print $1 }') \
-== $(sha512sum "${DISTDIR}/dists/${STAGE3TB}" |  awk -F ' ' '{ print $1 }') ]] && echo -e "[\e[32m*\e[0m] Verifying \e[35msha512sums\e[0m" \
+[[ $(grep -A 1 -i sha512 "${CDISTDIR}/dists/stage3-${ARCH}-latest.tar.bz2.DIGESTS.asc" | head -n 2 |grep stage3 | awk -F ' ' '{ print $1 }') \
+== $(sha512sum "${CDISTDIR}/dists/stage3-${ARCH}-latest.tar.bz2" |  awk -F ' ' '{ print $1 }') ]] && echo -e "[\e[32m*\e[0m] Verifying \e[35msha512sums\e[0m" \
 || echo -e "[\e[31m*\e[0m] \e[31mFAILD\e[0m: Verifying \e[31msha512sums\e[0m"
 sinit_mon 3
+fi
+elif [[ -e "${CDISTDIR}/dists/stage3-${ARCH}-latest.tar.bz2" ]]; then
+	echo -e "[\e[33m*\e[0m] Using local stage"
+else 
+	echo -e "[\e[31m*\e[0m] \e[31mFAILD\e[0m: \e[31mCould not located local stage\e[0m"
+	return 1
 fi
 unset VERIFICATION
 }
 
 [[ "$1" == "seed" ]] && seed_f
 
-if [[ "$(awk -F '=' '/CATALYST/{ print $2 }' < "${LOCALLG}/sinprog")" == 0 ]]; then
+if [[ "$(awk -F '=' '/CATALYST/{ print $2 }' < "${CLOCALLG}/sinprog")" == 0 || "$(awk -F '=' '/LOCALRB/{ print $2 }' < "${CLOCALLG}/sinprog")" == 0 ]]; then
+
 case "$2" in
 	catalyst)
 		# CATALYST
@@ -124,12 +185,12 @@ case "$2" in
 		sleep 0.5
 
 		if init_stage3_seq "$@"; then
-			sinit_mon 7
+			sinit_mon catalyst
 			echo "The build was successful!"
 			echo -e "\e[35mDo you wish to gpg sign the stage3 tarball?\e[0m"
 			while true; do
 				read -rp "Answer: Y/N " YN
-				case "$YN" in
+				case "${YN:-n}" in
 					[yY][eE][sS]|[yY])
 						echo "Signing..."
 						gpg --sign "${CATDIR}/builds/${TARGETPATH}/stage3-amd64-${TARGETSTAMP}.tar.bz2" \
@@ -144,28 +205,30 @@ case "$2" in
 				esac
 			done
 		else
-			sinit_mon catalyst
+			echo -e "\e[31mFAILED\e[0m" && return 1
 		fi
 		;;
 	localrb)
 		local_rbuild
 		sinit_mon catalyst;;
 esac
+else
+	echo -e "\e[33mPART A: Has been completed\e[0m"
 fi
 
 # Extract the tarball
-if [[ "$(awk -F '=' '/EXTRACTION/{ print $2 }' < "${LOCALLG}/sinprog")" == 0 ]]; then
+if [[ "$(awk -F '=' '/EXTRACTION/{ print $2 }' < "${CLOCALLG}/sinprog")" == 0 ]]; then
 
-CATDIR=$(grep storedir "${CONFDIR}/system/catalyst/catalyst.conf" \
+CATDIR=$(grep storedir "${CCONFDIR}/system/catalyst/catalyst.conf" \
 | sed '/^#/ d' | awk -F '=' '{ print $2 }' | sed  -e "s_\"__g")
 
-TARGETNAME="$(grep 'snapshot:' "${CONFDIR}/system/catalyst/stage1.spec" \
+TARGETNAME="$(grep 'snapshot:' "${CCONFDIR}/system/catalyst/stage1.spec" \
 | sed '/^#/ d' | sed '/^\s*$/d' | awk -F ' ' '{ print $2 }' | sed  -e "s_\"__g")"
 
-TARGETPATH="$(grep 'source_subpath' "${CONFDIR}/system/catalyst/stage3.spec" \
+TARGETPATH="$(grep 'source_subpath' "${CCONFDIR}/system/catalyst/stage3.spec" \
 | sed '/^#/ d' | awk -F ' ' '{ print $2 }' | sed  -e "s_\"__g" | awk -F '/' '{ print $1 }')"
 
-TARGETSTAMP="$(grep 'version_stamp' "${CONFDIR}/system/catalyst/stage3.spec" \
+TARGETSTAMP="$(grep 'version_stamp' "${CCONFDIR}/system/catalyst/stage3.spec" \
 | sed '/^#/ d' | awk -F ' ' '{ print $2 }' | sed  -e "s_\"__g")"
 
 extract_tarball() {
@@ -185,9 +248,10 @@ tar xvjpf "$1" -C "$2" --xattrs --numeric-owner >/dev/null 2>&1 \
 check_dir() {
 if [[ -d "$2" ]]; then
 while true; do
-	echo "Seems that $2 already exists"
-	echo "Continue, backup as old or purge? "
-	read -rp "Answer CONTINUE/OLD/PURGE " ANS
+	echo -e "Seems that there already has been done some work at the \e[34mbuilderdir\e[0m"
+	echo "You could either continue from where you left, or backup/purge then start anew"
+	echo -e "Give one of: \e[32mCONTINUE\e[0m/\e[34mOLD\e[0m/\e[31mPURGE\e[0m "
+	read -rp "Input :: <= " ANS
 	case $ANS in
 		OLD)
 			echo "Backing up..."
@@ -219,11 +283,11 @@ fi
 case "$2" in
 	catalyst)
 		check_dir "${CATDIR}/builds/${TARGETPATH}/stage3-amd64-${TARGETSTAMP}.tar.bz2" \
-		"${DISTDIR}/stage3-amd64-${TARGETSTAMP}-${GSEVER}" \
+		"${CDISTDIR}/stage3-amd64-${TARGETSTAMP}-${GSEVER}" \
 		"${CATDIR}/snapshots/portage-${TARGETNAME}.tar.bz2"
 		;;
 	precomp)
-		check_dir "${DISTDIR}/dists/${STAGE3TB}" "${DISTDIR}/stage3-amd64-latest-${GSEVER}"
+		check_dir "${CDISTDIR}/dists/${STAGE3TB}" "${CDISTDIR}/stage3-amd64-latest-${GSEVER}"
 		;;
 esac
 unset EXTRACTION
@@ -232,7 +296,7 @@ sinit_mon 4
 fi
 
 # PART B
-[[ "$(awk -F '=' '/PARTB/{ print $2 }' <"${LOCALLG}/sinprog")" == 0 ]]
+[[ "$(awk -F '=' '/PARTB/{ print $2 }' <"${CLOCALLG}/sinprog")" == 0 ]]
 echo
 echo "============================================================================"
 echo -e "\e[35mPART:B Preparing to enter the new system\e[0m"
@@ -287,12 +351,12 @@ mount --rbind /sys "$1/sys" \
 
 mkdir -p "$1/sinit.d"
 
-rsync -avhPr "${WORKDIR}/scripts/chroot_scripts/" "$1/sinit.d/" >/dev/null 2>&1 \
-&& rsync -a "${CONFDIR}/system/portage/make.conf" "$1/sinit.d/" >/dev/null 2>&1 \
-&& rsync -a "${CONFDIR}/system/portage/package.use/sysbuild" "$1/sinit.d/" >/dev/null 2>&1 \
-&& rsync -a --exclude="portage" "${CONFDIR}/system/" "$1/sinit.d/" >/dev/null 2>&1 \
-&& echo -e "[\e[32m*\e[0m] Copying required files to new system" \
-|| { echo -e "[\e[31m*\e[0m] Copying required files to new system"; return 1; }
+[[ ! -e "$1/sinit.d/chsinprog" ]] && rsync -aAXr "${CWORKDIR}/scripts/chroot_scripts/" "$1/sinit.d/" >/dev/null 2>&1 \
+|| rsync -aAXr --exclude="chsinprog" "${CWORKDIR}/scripts/chroot_scripts/" "$1/sinit.d/" >/dev/null 2>&1 \
+&& rsync -aAXr "${CCONFDIR}/system/portage/" "$1/sinit.d/" >/dev/null 2>&1 \
+&& rsync -aAXr --exclude="portage" "${CCONFDIR}/system/" "$1/sinit.d/" >/dev/null 2>&1 \
+&& echo -e "[\e[32m*\e[0m] Copying \e[34mbuilder's\e[0m files to new system" \
+|| { echo -e "[\e[31m*\e[0m] Copying \e[34mbuilder's\e[0m files to new system"; return 1; }
 
 # CREATE REPOS.CONF DIRECOTRY & AND COPY REPOS.CONF TO IT
 mkdir -p "$1/etc/portage/repos.conf"
@@ -306,12 +370,12 @@ unset TIMEZONE
 fi
 
 echo -e "[\e[32m*\e[0m] Copying requested files"
-if [[ -n $(cat ${CONFDIR}/system/inject_files | sed '/^#/ d' | sed '/^\s*$/d') ]]; then
+if [[ -n $(cat ${CCONFDIR}/system/inject_files | sed '/^#/ d' | sed '/^\s*$/d') ]]; then
 
 while read -r INJFL;do
 	echo "Copying $($INJFL | awk -F ' ' '{ print $1 }') to $($INJFL | awk -F ' ' '{ print $2 }')"
 	rsync -aAXPhrv ${INJFL} >/dev/null 2>&1 && print_inf 1 || { print_inf 2 mapfile -t INJFLERR < <($INJFL | awk -F ' ' '{ print $1 }'); }
-done < <(cat "${CONFDIR}/system/inject_files" | sed '/^#/ d' | sed '/^\s*$/d')
+done < <(cat "${CCONFDIR}/system/inject_files" | sed '/^#/ d' | sed '/^\s*$/d')
 unset INJFL
 echo "Failed to copy the following packages: "
 echo "${INJFLERR[@]}"
@@ -360,32 +424,31 @@ fi
 echo -e "\e[34mChrooting at new system\e[0m"
 sleep 2
 chroot "$1" "sinit.d/chroot_init" "$@" || { echo -e "[\e[31m*\e[0m] Chrooting at new system"; return 1; }
-rm -rf "$1/sinit.d"
 sinit_mon 6
 }
 
-TARGETSTAMP="$(grep 'version_stamp' "${CONFDIR}/system/catalyst/stage3.spec" \
+TARGETSTAMP="$(grep 'version_stamp' "${CCONFDIR}/system/catalyst/stage3.spec" \
 | sed '/^#/ d' | awk -F ' ' '{ print $2 }' | sed  -e "s_\"__g")"
 
 case "$2" in
 	catalyst)
-		pr_chroot_f "${DISTDIR}/stage3-amd64-${TARGETSTAMP}-${GSEVER}";;
+		pr_chroot_f "${CDISTDIR}/stage3-amd64-${TARGETSTAMP}-${GSEVER}" "${RREQ}";;
 	precomp)
-		pr_chroot_f "${DISTDIR}/stage3-amd64-latest-${GSEVER}";;
+		pr_chroot_f "${CDISTDIR}/stage3-amd64-latest-${GSEVER}" "${RREQ}";;
 esac
 exit
 case "$2" in
 	catalyst)
-		tar cvf "${DISTDIR}/stage3-amd64-${TARGETSTAMP}-${GSEVER}.tar.bz2" -C "${DISTDIR}/stage3-amd64-${TARGETSTAMP}-${GSEVER}";;
+		tar cvf "${CDISTDIR}/stage3-amd64-${TARGETSTAMP}-${GSEVER}.tar.bz2" -C "${CDISTDIR}/stage3-amd64-${TARGETSTAMP}-${GSEVER}";;
 	precomp)
-		pr_chroot_f "${DISTDIR}/stage3-amd64-latest-${GSEVER}.tar.bz2" -C "${DISTDIR}/stage3-amd64-latest-${GSEVER}";;
+		pr_chroot_f "${CDISTDIR}/stage3-amd64-latest-${GSEVER}.tar.bz2" -C "${CDISTDIR}/stage3-amd64-latest-${GSEVER}";;
 esac
 sinit_mon 7
 exit
 
 gpg --armor --export email > ${FINALDIST}/key.asc # THIS WILL BE ADDED TO THE HOSTS
 gpg --detach-sign -o ${GSE_VER}.gpg ${FINALDIST}/${IMAGE}
-
+#rm -rf "$1/sinit.d"
 unset CATDIR
 unset TARGETPATH
 unset TARGETSTAMP
